### ISSUE TITLE
Without compatibility issue  and flags

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win#10]
Hello, I still prefer to wait for the problem of compatibility with windows 10 to be resolved by default and without user intervention before using the excellent Thorium Browser as my main browser, and I suggest that while waiting for this bug to be resolved that Mr lex make a chromium version with avx or avx2 and fma not very advanced technically and sophisticated, a version has been modified too much in order to avoid compatibility problems, I say that I recently tested a chromium version with avx and fma but not as modifed as Thorium browser and I noticed that the fan of my computer does not turn any more and does not produce any more noise! ​​therefore the version with fma and avx seems to solve the problem of the annoying activation of the fan that's why I suggested that Mr. Alex make a more basic version of Thorium browser in order to solve all the compatibility problems.....

I went to discover the chromium flags and I discovered several superfluous flasg for me and that we can deactivate, by exp Tab Hover Card Images, the NTP flags, mirroring, prerender... I learned about all these flags and my browser works fast and without bugs, I suggest that Tohrium make a special version or add an option to disable, for example, all experimental flags such as experimental javascript, smooth scrolling....thus the notebook battery will be preserved.....thank you

**Comment by Alex313031** [comment]
@trimechee The compatibility mode issue has been fixed.

I will not be making changes to the above flags, as the affect on performance is miniscule and some people want them. I use the hover card images and prerendering for example.

**Comment by trimechee** [comment]
Great ! thank you very much ! yes i understand , you are right,  these flags could be be necessary and the affect on performance is miniscule....

I went to the bios to disable unnecessary options and I disabled Intel AES-NI which is apparently used for encryption and decryption then I tried to open the browser which has avx2 and fma enabled, but the browser doesn't open,  however i can open microsoft edge browser,  so AES-NI is needed for chromium avx2 and fma to work?


I have already asked the question to another developer but I am asking the question again to have your opinion on this subject please : does Thorium Browser support HEVC?
and since avx2 and fma are enbaled in Thorium browser, does their activation lead to overconsumption of electricity and excessive power thus the fan of the computer will run longer and more noisy?

**Comment by Alex313031** [comment]
@trimechee  Thorium needs AES, as it is a requirement to build with AVX or AVX2. Why did you disable it? AES-NI is a good thing, Thorium uses it to speed up AES encryption and decryption, which is normally done in software and is taxxing on the CPU.

Thorium does support HEVC, but your GPU must support decrypting it.

FMA and AVX have no effect. It is possible that AVX2 might make your CPU hotter, but I doubt that thorium is making your fan run faster. If in doubt, you could use the regular Thorium Win release with just AVX.

**Comment by Alex313031** [comment]
@trimechee Compatibility issue has been fixed.

**Comment by trimechee** [comment]
Great ! thank you very much :) now we hope that our beloved Thorium Browser will find a solution ti disable completely session store restore to save SSD life and battery 🥇
