### ISSUE TITLE
Issues with Tabs not showing at the top

### ISSUE THREAD

**Issue by Nick-Espinosa** [Alex313031/Thorium-Win#104]
**System Details**
 - OS: Windows 11 Enterprise
 - Thorium Version Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
Tabs on my work machine are not showing and for the life of me I cannot figure out how to get them to show like normal.
I never changed a setting or option, it has been like this from the beginning. 
I installed on my personal machine and it showed the tabs like normal from the start.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/148775684/1f1e6ab8-f970-4fed-bc23-a2023c23abb4)
![image](https://github.com/Alex313031/Thorium-Win/assets/148775684/1835a958-4e51-4b36-8f24-1385cbfd0be3)

**Additional Notes**
If this is a user error please forgive me haha, thanks for the sick browser!

**Comment by gz83** [comment]
#91

**Comment by Nick-Espinosa** [comment]
Awesome, thanks for the quick response and help, after disabling Touch UI Layout we are good to go!
