### ISSUE TITLE
Keep support for "RendererCodeIntegrity"

### ISSUE THREAD

**Issue by jonm58** [Alex313031/Thorium-Win#105]
Starting from Chrome 78, Chrome began to prevent third-party DLL injection, and now Chrome 118 has completely failed.
I like [MacType](https://github.com/snowie2000/mactype) cannot inject DLL in 118+

[RendererCodeIntegrity](https://chromeenterprise.google/policies/?policy=RendererCodeIntegrityEnabled)

**Comment by gz83** [comment]
Allowing DLL injection will indeed bring a lot of convenience, we will consider it and evaluate the risks

**Comment by jonm58** [comment]
> 允许DLL注入确实会带来很多便利，我们会考虑并评估风险

OK,Thanks
