### ISSUE TITLE
How to configure policies/preferences for Thorium Browser 

### ISSUE THREAD

**Issue by rayshabh** [Alex313031/Thorium-Win#107]
I'm trying to enforce some policies/preferences to suit my needs. Below is the list of policies I'm trying to enforce:-
```
"ClearBrowsingDataOnExit": true,
"ConfigureDoNotTrack": true,
"DnsOverHttpsMode": "secure",
"DnsOverHttpsTemplates": "https://chrome.cloudflare-dns.com/dns-query",
"EfficiencyMode": 1,
"EnhanceSecurityMode": 0,
"HardwareAccelerationModeEnabled": true,
"InPrivateModeAvailability": 2
```
How do I deploy these policies for Thorium browser on Windows & Linux as I use both OSes.

**Comment by gz83** [comment]
It is similar to configuring policies for Chrome, but note that it needs to be done under the Thorium folder or registry.

Some policies should be settable through the interface.

**Comment by rayshabh** [comment]
> It is similar to configuring policies for Chrome, but note that it needs to be done under the Thorium folder or registry.
> 
> Some policies should be settable through the interface.

Yup. Set! But it needs to be done by making a new folder "Chromium" i.e. `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium`. 

### **Thorium Folder does not work!**
