### ISSUE TITLE
[BUG] Thorium crashes in settings page

### ISSUE THREAD

**Issue by wrestlerdude** [Alex313031/Thorium-Win#11]
# System Information
- OS: Windows 10
- Thorium Version: 105.0.5166.0

# Observable Problem
When I go into `chrome://settings` and I use the 'Search settings' feature, after a few characters my browser unexpectedly closes. Also, this happened on a fresh install without any extensions added.

# Video
https://user-images.githubusercontent.com/26298518/180096710-209a12c5-c947-4302-b5a2-9b0e8a807356.mp4

**Comment by Alex313031** [comment]
@wrestlerdude Yeah, this has been a problem for a while now.

**Comment by Alex313031** [comment]
@wrestlerdude Me and @gz83 are working on it.

**Comment by Alex313031** [comment]
@wrestlerdude It has been fixed! > https://github.com/Alex313031/Thorium-Win/releases/tag/M106.0.5219.0

**Comment by wrestlerdude** [comment]
> @wrestlerdude It has been fixed! > https://github.com/Alex313031/Thorium-Win/releases/tag/M106.0.5219.0

Thank you!
