### ISSUE TITLE
Horrible mobile like tabs. Please bring back traditional tabs.

### ISSUE THREAD

**Issue by BODYPRINT** [Alex313031/Thorium-Win#110]
The heading says it all!

![image](https://github.com/Alex313031/Thorium-Win/assets/734141/545dab41-d0ac-4ef4-be4e-e632c7f0fc7a)

**Comment by gz83** [comment]
Go to chrome://flags to turn off TOUCH UI

**Comment by BODYPRINT** [comment]
Perfect, thank you :)
