### ISSUE TITLE
Some UI Suggestions

### ISSUE THREAD

**Issue by mousethatischarles** [Alex313031/Thorium-Win#112]
Hi,
I've been a long-standing user of Vivaldi but have gotten a little frustrated by it's instability on my system and have been quite taken by Thorium being very more stable and rather faster. There are however a few features I really miss, I'd be grateful if the developer(s) might consider adding them to Thorium.
1) Editable Tool Bar Icons - I do like a minimalist setup and have my current browser set just as I like it. In Vivaldi a Right-Click on any icon will bring up a menu either to remove it or bring up an editor to move / remove / change icons.
2) There seems to be no way to hide the default 'experiments', 'side panel', and 'avatar' icons behind the 'Extensions' icon or remove them entirely.
3) Vivaldi's optional blocking of trackers and ads icon / indicator to the left of the address bar is a useful feature for me... I'm aware Thorium includes add-blocking as a built in extension but I find this more intuitive.
4) Vivaldi's 'Start Page' feature for new tabs is rather more useful than Thorium's 'New Tab' page for me - I'm aware I could just add another extension but most are overblown with unnecessary 'features' when iconified links to a special folder within my bookmarks is all I want / need.
5) Just about every 'feature' in Vivaldi can be turned off / on, or moved - very useful to me as that browser comes with a lot of annoying stuff like icons or pesky side-bars that pop-up that I neither want nor need. Thorium has rather less such bloat but there are still a few such 'features' it would be nice if I could optionally turn off entirely. Maybe via a context menu or an edit panel in settings?

Thank you for all your hard work, I really am most impressed with Thorium. Apologies if some of the above is already present, I just haven't located it yet.

Kind Regards,

**Comment by gz83** [comment]
There is currently no way to choose to hide or show the icons above the toolbar like Vivaldi does.

The lab, sidepanel, and avatar icons can be turned off in chrome://flags, which corresponds to the experimental flags Chrome Labs, Hide Side Panel Button, and Show/Hide the Avatar Button.

Finally, thank you very much for the other suggestions, we will take them into consideration.

**Comment by mousethatischarles** [comment]
Thank you for your helpful reply, I very much appreciate it.
Apologies for my slow reply in return.

Very much enjoying Thorium.

Kind Regards,
Charles.

qubeserver.rf.gd/art3/

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by cjpdee** [comment]
Just adding my support for this - being able to hide the address bar is the only reason I use Vivaldi over thorium. Would love to see this, I'd 100% make the switch

**Comment by Alex313031** [comment]
@gz83 @cjpdee @mousethatischarles Yeah, those three buttons can be removed with a flag.

The new tab page can be set to anything your heart desires by using the `chrome://flags/#custom-ntp` flag I added from Ungoogled-Chromium.

Editable toolbar icons is probably not something I will implement, as there is already so many files I have to modify to keep the current tabstrip flags working. This is assuming I could even get it right and get it to compile correctly.
