### ISSUE TITLE
Hotkey Customization for Bookmark All Tabs

### ISSUE THREAD

**Issue by SpaceAudits** [Alex313031/Thorium-Win#113]
On Chrome a user can press CTRL+SHIFT+D and an option to bookmark all open tabs appears. On Thorium CTRL+SHIFT+D seems to open a duplicate tab of the current window.

My question and/or suggestion: is it possible to remap CTRL+SHIFT+D on Thorium to have the same functionality as Chrome.

I know this isn't a high priority and you're probably mad busy. If there's a way to do it in :config or something, hit me up and can figure it out from there.

Thanks so much. I'm really enjoying the browser.

**Comment by gz83** [comment]
It seems that the shortcut key for this function has been modified in the code. I will forward it to Alex to check this issue.

@SpaceAudits @Alex313031

**Comment by ho77iday** [comment]
Can we have this on Ubuntu too? I bookmark sites quite often, but opening duplicate tabs has been... never

**Comment by Alex313031** [comment]
@SpaceAudits @ho77iday @eltociear I can add a flag to control this, however it won't be until next Thorium release since M130 is almost done and we are releasing that tommorow.
