### ISSUE TITLE
Virus Total Report for URL and EXE Check - Please Resolve

### ISSUE THREAD

**Issue by mayakot98** [Alex313031/Thorium-Win#122]
Dear Sir,

I have watached the video on Chirs Titus youtube channel and installed it on the system. the browser feels nice but since I want to open some banking website so I thought to check once for virus on virus total webite and below are the results from the virus total webite.

Please remove the bugs & correct the EXE so it will not show the warning on the visus total website.

**Result for URL Check on the Wesite provided**

![Screenshot_1](https://github.com/Alex313031/Thorium-Win/assets/102904701/08fe2d64-f30f-4b50-bec4-9a6edd7b28f0)

**Result When I installled it on system and checked its EXE from virus total.**
![Screenshot_3](https://github.com/Alex313031/Thorium-Win/assets/102904701/91532d0f-5117-4d02-ae10-3236c6e8044e)
![Screenshot_2](https://github.com/Alex313031/Thorium-Win/assets/102904701/4e55c08b-9470-4159-92ed-2cc36ea3f017)
![Screenshot_4](https://github.com/Alex313031/Thorium-Win/assets/102904701/a65397d6-98f2-4989-8913-0c75ff6d608e)
![Screenshot_5](https://github.com/Alex313031/Thorium-Win/assets/102904701/f93d301b-cf7f-4df9-8dd5-2e474ac60225)

**Comment by gz83** [comment]
Mark as duplicate
