### ISSUE TITLE
Pixelated Text

### ISSUE THREAD

**Issue by qimoeee** [Alex313031/Thorium-Win#123]
**System Details**
 - OS: Windows 11 
 - Thorium Version M117.0.5938.157

**Problem**
Whenever I open a new tab or stay on a tab, the text gets weird and becomes pixelated. I'm not sure if this is correlated but sometimes there are artifacts that show up on images and text too, second screenshot is an example of that.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/140006926/19419700-b9d6-456a-87f4-4ac08e9acf2c)
![image](https://github.com/Alex313031/Thorium-Win/assets/140006926/54d5e3d3-7ef4-4b9e-a4bb-1ca7d62711c5)

**Comment by gz83** [comment]
Mark as duplicate
