### ISSUE TITLE
Qol's

### ISSUE THREAD

**Issue by stl3** [Alex313031/Thorium-Win#126]
These are just qol's and very low priority but I think they could be useful, at least as ideas.

#### Memory Saver
Toggle to enable/disable per site from it's settings so I don't need to add/remove when needed. I know a lot of people probably don't need this but there are certain scenarios (like when I need a collab tab active or just dormant in background). Perhaps access to right-click context on tab to enable/disable memory saver if it has a matching entry?

#### Save tabs as session
I found this feature on some other browser to be very valuable (at least in my use case, where I can also load/save tabs in normal/private mode). I usually need a bunch of tabs for work related stuff in private tabs.

#### Ability to set key to bind to translate
Let user define a hotkey for translate.

**Comment by gz83** [comment]
Chrome/Chromium currently supports the memory saving function. This function is currently located on the settings page.

Thanks for the other suggestions as well.

**Comment by stl3** [comment]
That is correct. Currently the memory saver options page has options like Add/Edit/Remove. With my suggestions it would have additional options like Add/Edit/Enable|Disable/Remove or perhaps look something like this if one were to right-click on the tab:
(assuming the site has an entry matching in Memory Saver options)

```
... additional tab menu options ...
Reload
Duplicate
Pin
Mute site
Enable/Disable memory saver
```

**Comment by gz83** [comment]
Thorium will not modify the memory saving function at this time, and Google is still modifying this function.
