### ISSUE TITLE
1password extension doesn't get desktop app status

### ISSUE THREAD

**Issue by macedonsky777** [Alex313031/Thorium-Win#129]
**System Details**
 - OS: [Windows 11]
 - Thorium Version [117.0.5938.157]

**Problem**
1Password extension doesn't see that password was already entered in desktop app and want to enter it again.

**Additional Notes**
In all other browsers connection between extension and desktop app works correctly.

**Comment by MagmaBro123** [comment]
This project might be abandonware, don't expect this to be fixed.

**Comment by regix1** [comment]
Having the same problem

**Comment by T00dl3sDE** [comment]
Unfortunately it didn't work for me.
I am also on the latest 1Password Beta (1Password for Windows 8.10.24 (81024006)) and Thorium AVX2 (Version 117.0.5938.157)
Also did try it with the Stable and Beta Extensions. Always says "Problems connecting..."
Does someone has any other Ideas ?

**Comment by Alex313031** [comment]
@MagmaBro123 Can you please halt posting on issues with "this project is dead" stuff.

**Comment by Alex313031** [comment]
@macedonsky777 Please see https://github.com/Alex313031/thorium/issues/316 and https://github.com/Alex313031/thorium/issues/287#issuecomment-1780551726 for solution.

You may also have to set nativemessaginghosts like so (modify the strings for this though, not bitwarden)
https://github.com/Alex313031/thorium/issues/363#issuecomment-1783851037

This is often needed for Chromium (and Chromium based browsers)

 And no @macedonsky777 @MagmaBro123 This project is not abandonware or dead by any means. I was just in the hospital for a month.

**Comment by macedonsky777** [comment]
> @macedonsky777 Please see [Alex313031/thorium#316](https://github.com/Alex313031/thorium/issues/316) and [Alex313031/thorium#287 (comment)](https://github.com/Alex313031/thorium/issues/287#issuecomment-1780551726) for solution.
> 
> You may also have to set nativemessaginghosts like so (modify the strings for this though, not bitwarden) [Alex313031/thorium#363 (comment)](https://github.com/Alex313031/thorium/issues/363#issuecomment-1783851037)
> 
> This is often needed for Chromium (and Chromium based browsers)
> 
> And no @macedonsky777 @MagmaBro123 This project is not abandonware or dead by any means. I was just in the hospital for a month.

Thanks, I will check soon, but I recognized that in mozilla based Floorp the same issue :D so, not just Chromium based))

**Comment by regix1** [comment]
I found this to be an issue with the latest version:

![image](https://github.com/Alex313031/Thorium-Win/assets/7908370/9bdc62ee-3c2d-4790-a9d5-deea685db9bc)

I was able to spoof my browser using AdGuard for Desktop to the latest version `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36`:

![image](https://github.com/Alex313031/Thorium-Win/assets/7908370/73609bb8-6387-452b-9406-91a51978b7a3)

And this fixed my issue with the connection to the Desktop 1Password App.
