### ISSUE TITLE
Resources Saver , energy consumption, battery saver

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win#13]
Hello, i discover with great pleasure and joy I  your awesome magnificent exceptional extension: Resources Saver!

https://chrome.google.com/webstore/detail/resources-saver/nlfcijlhljpenllloeheihmhoobeefpc?hl=en&authuser=0

Thanks a lot !

and therefore this extension can register an entire website? even with videos?

in changelog: "Built with new optimization: Polly
You can see a write up of the optimizations Thorium uses (including the new Polly) Here, and a page with speed comparisons with screenshots Here. I compare Thorium against Chromium, Chrome, Brave, and Vivaldi."

congratulations, this performance gain and the superiority of Thorium browser over other famous browsers is very impressive!!

just a question, if the performance is superior, then Thorium Browser uses more energy than other browsers in normal use?

If so, and because sometimes the battery gets low and extend laptop battery Life, I make a suggestion even though I know it's very complicated! it will be great if our bleoved Thorium browser add battery saver like in opera browser, yandex browser, and edge browser, thank you very much!

"Beat the heat during summer
There is one more thing we realized recently. If something consumes more energy, it usually gets warmer – basic physics. That's why your laptop gets overheated during your heavy browsing sessions. This heats up your lap, sets off a loud and annoying fan, and can cause problems such as random blue screens or even data loss.

We've made tests comparing the temperature of the bottoms of two laptops. One was running Opera with battery saver enabled and the other one Opera with the mode disabled. Test results with the new battery saver enabled showed that Opera can keep laptops over 3 degrees (C) cooler. It's actually pretty nice difference, especially when you think about bringing your laptop along for summer fun and letting it bake your lap.

Improvements under the hood
Wonder how we achieved this cool down and power savings? With several under-the-hood optimizations:

Reducing activity in background tabs
 

Waking CPU less often due to optimal scheduling of JavaScript timers
 

Automatically pausing unused plug-ins
 

Reduced frame rate to 30 frames per second
 

Tuning video-playback parameters and forcing use of hardware accelerated video codecs
 

Pausing animations of browser themes
 

Including ad blocker – when enabled, it enables even more battery savings"

https://blogs.opera.com/desktop/2016/06/battery-saver-opera-browser-for-windows-mac/

**Comment by Alex313031** [comment]
@trimechee The resources saver extension will save an entire webpage, including the directory structure, and files that are missed by just using the built in "Save As". It will save videos, but only if they are using the <video> element in HTML. If it is using an iframe, or encrypted streams (like netflix) it cant save them.

**Comment by trimechee** [comment]
Great ! thank you ! please if there is cpu throttle or energy saver, please give option to users to choose to enable this option for all the time even even when plugged in sector, because opera and yandex and naver browsers do not give the choice when plugged, on the other hand edge browser gives us the choice to enable for always this opton to save energy even plugged, beacause we may have laptop that are too weak.....

**Comment by Alex313031** [comment]
@trimechee Interestingly, Chromium is actually adding this upstream with M108. So I wont even have to do any work, it should just be a feature for thorium releases next month when M108 comes out.

**Comment by trimechee** [comment]
Well done ! thank you :)
