### ISSUE TITLE
Unable to stream Netflix on Thorium

### ISSUE THREAD

**Issue by SupaWasHere** [Alex313031/Thorium-Win#132]
**System Details**
 - OS: Windows 11 Pro
 - Thorium Version: 117.0.5938.157

**Problem**
When on Netflix, I cannot stream shows/movies on the website on Thorium. I have tried on normal Chrome, and it works fine. When i try adding a show to 'My List', it logs me out of Netflix. When i go to play a show or movie, it too logs me out of Netflix. It doesn't do this on Chrome. It use to show an error message saying it was not a supported browser, but now it just logs me out. I have tried disabling all extensions, dns and setting other privacy settings to default, and issue still occurs. Unsure if this issue is happening on other streaming sites, as I haven't tested that.

**Screenshots**
I don't have a screenshot of the error message as it use to say it about a week ago, but now it just logs me out.

**Additional Notes**
Nothing to add here.

**Comment by MagmaBro123** [comment]
This project might be abandonware, don't expect this to be fixed.

**Comment by rayshabh** [comment]
> **System Details**
> 
> * OS: Windows 11 Pro
> * Thorium Version: 117.0.5938.157
> 
> **Problem** When on Netflix, I cannot stream shows/movies on the website on Thorium. I have tried on normal Chrome, and it works fine. When i try adding a show to 'My List', it logs me out of Netflix. When i go to play a show or movie, it too logs me out of Netflix. It doesn't do this on Chrome. It use to show an error message saying it was not a supported browser, but now it just logs me out. I have tried disabling all extensions, dns and setting other privacy settings to default, and issue still occurs. Unsure if this issue is happening on other streaming sites, as I haven't tested that.
> 
> **Screenshots** I don't have a screenshot of the error message as it use to say it about a week ago, but now it just logs me out.
> 
> **Additional Notes** Nothing to add here.

Please check this [Issues #73](https://github.com/Alex313031/Thorium-Win/issues/73) and scroll down and find why Thorium is unable to play videos that are **DRM protected**.

**Comment by Alex313031** [comment]
@SupaWasHere Yeah, what @rayshabh said lol.

**Comment by LukasExemplar** [comment]
> This project might be abandonware, don't expect this to be fixed.

It's not. What the hell are you on about??????? You should delete this comment, it's embarassing, rude and feels spammy.

**Comment by MagmaSlime123** [comment]
> > This project might be abandonware, don't expect this to be fixed.
> 
> It's not. What the hell are you on about??????? You should delete this comment, it's embarassing, rude and feels spammy.

At the time I thought it was. I wasn't aware @Alex313031 was at a hospital before he made his post on where he was. He had no PC at the time.

I am sorry, and that's that.
