### ISSUE TITLE
0xc0000142

### ISSUE THREAD

**Issue by Huyenne123** [Alex313031/Thorium-Win#136]
**System Details**
 - OS: Windows 11 (atlasOS 11)
 - Thorium Version 117.0.5938.157

**Problem**
The application was unable to start correctly (0xc0000142). Click OK to close the application. 

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/87600660/1d3ece8d-afeb-42ce-816e-34611286865c)

**Additional Notes**

**Comment by glisovic01** [comment]
Same problem here, the only thing different is that I am using Win 10.

**Comment by SheMelody** [comment]
I confirm that this is indeed a problem, and it happens on relatively "old" processors apparently.

**Comment by qzmtch** [comment]
> **System Details**
> 
> * OS: Windows 11 (atlasOS 11)
> * Thorium Version 117.0.5938.157
> 
> **Problem** The application was unable to start correctly (0xc0000142). Click OK to close the application.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/87600660/288959244-1d3ece8d-afeb-42ce-816e-34611286865c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODk2MDIsIm5iZiI6MTcwMjQ4OTMwMiwicGF0aCI6Ii84NzYwMDY2MC8yODg5NTkyNDQtMWQzZWNlOGQtYWZlYi00MmNlLTgxNmUtMzQ2MTEyODY4NjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE3NDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjA1ODAzYjllYjM3MGZlMGNmNWEwYTBmYjFiODk5MTNkNmIzOWM2NzM4MjM5NDJlMDBlYzRjMDM4NGZmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLvZwmPVBeZfufJb8V39i2IO7Y3eJ5UqvS9XW9mXEeY)
> 
> **Additional Notes** Add any other context about the problem here.

https://github.com/Alex313031/Thorium-SSE3/releases

**Comment by SheMelody** [comment]
> > **System Details**
> > 
> > * OS: Windows 11 (atlasOS 11)
> > * Thorium Version 117.0.5938.157
> > 
> > **Problem** The application was unable to start correctly (0xc0000142). Click OK to close the application.
> > **Screenshots** ![image](https://private-user-images.githubusercontent.com/87600660/288959244-1d3ece8d-afeb-42ce-816e-34611286865c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0ODk2MDIsIm5iZiI6MTcwMjQ4OTMwMiwicGF0aCI6Ii84NzYwMDY2MC8yODg5NTkyNDQtMWQzZWNlOGQtYWZlYi00MmNlLTgxNmUtMzQ2MTEyODY4NjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE3NDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjA1ODAzYjllYjM3MGZlMGNmNWEwYTBmYjFiODk5MTNkNmIzOWM2NzM4MjM5NDJlMDBlYzRjMDM4NGZmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLvZwmPVBeZfufJb8V39i2IO7Y3eJ5UqvS9XW9mXEeY)
> > **Additional Notes** Add any other context about the problem here.
> 
> https://github.com/Alex313031/Thorium-SSE3/releases

I figured this out 2 minutes afterwards I posted my response. No idea why there is nothing in the ReadMe stating that Thorium-Win is also AVX.

**Comment by Alex313031** [comment]
@SheMelody @qzmtch @Huyenne123 @glisovic01 @eltociear @gz83
This is because Thorium requires AVX.
However, in the latest M119 build I added SSE3 releases for Windows and Linux.

@SheMelody I will update the Readme. Thanks.
