### ISSUE TITLE
why is it 197 gb???

### ISSUE THREAD

**Issue by darkerraven** [Alex313031/Thorium-Win#139]
![351E02GhCp](https://github.com/Alex313031/Thorium-Win/assets/115076107/d069680c-01df-4a79-aa22-a5ae2c513bd9)

**Comment by MagmaBro123** [comment]
This project is dead. Go back to Chrome.

**Comment by gz83** [comment]
Try clearing your browser data

**Comment by gz83** [comment]
> This project is dead. Go back to Chrome.

You can choose not to use this browser

**Comment by Alex313031** [comment]
@MagmaBro123 Not dead. I was simply in the hospital for a month without access to a computer.

**Comment by Alex313031** [comment]
@gz83  @darkerraven The installation is not this big, it must be your user profile. I am running it on Windows 10 as well, and often have 300+ tabs open spread across multiple windows, but my user profile never gets larger than 2GB. Chromium is supposed to hard limit it to 2GB, and I have never seen anything like this on any of the platforms.

Are you sure it is not a setting you are doing on your side, or perhaps a win10 modification? You can try clearing the browser cache/cookies. If it still does not resolve it, I would recommend deleting/recreating the user profile.

First, you can bookmark all your tabs and then go to chrome://bookmarks to export your bookmarks so you don't lose information (you will lose your browsing history and saved password though).
Then close thorium and delete the `C:\Users\$USERNAME\AppData\Local\Thorium\User Data` folder.

Relaunch, and you can import your bookmarks again by going to chrome://bookmarks and choosing the .html file that was exported before.
