### ISSUE TITLE
discussion: about a release like ungoogled chromium

### ISSUE THREAD

**Issue by debpalash** [Alex313031/Thorium-Win#14]
you work is promising, as an [ungoogled chromium](https://github.com/ungoogled-software/ungoogled-chromium-windows) user i'd ask you if you're interested in building a release where google/affiliates built in extensions, api and service calls are stripped down to make zero noise.

Thanks

**Comment by tomByrer** [comment]
I'd like a [more private browser](https://privacytests.org/) also; thought about merging with Brave.

**Comment by Alex313031** [comment]
@tomByrer @debpalash The goal of thorium is not to produce something ungoogled. I can more patches from ungoogled chromium and brave, and you guys are welcome to send patches you would like.

But Im never going to add patches that remove google sync, or web store support. I like to cherry pick patches from projects to make it more private and secure, but not at the cost of usability. Removing the web store, google search, or google sync affects useability.

**Comment by debpalash** [comment]
@Alex313031 I'm not into system dev otherwise i'd built my own chromium. Anyway do only if this idea interests you.

I was suggesting a separate build. It's because Thorium is performant than ungoogled, Thorium could be the next ungoogled chromium. If you make a separate repo where all the google stuff is removed, like adding privacy enhancements, bromite https://github.com/bromite/bromite, ungoogled https://github.com/macchrome/winchrome patches. Hibbiki already does both sync and no-sync releases, https://github.com/Hibbiki/chromium-win64/releases.
Thanks

**Comment by debpalash** [comment]
> It might be interesting to make an ungoogled thorium build. I cant promise that I would maintain it though

that’s understandable. good luck.
