### ISSUE TITLE
hardware acceleration bug

### ISSUE THREAD

**Issue by lukeea12** [Alex313031/Thorium-Win#141]
Windows 11
Thorium: 117.0.5938.157 (Build oficial) (64 bits)

When hardware acceleration is on, weird things happen. (found out about it on youtube, probably happens on other pages)

I also noticed that some text disappears randomly or greys out.

https://github.com/Alex313031/Thorium-Win/assets/147871385/2a9d4d96-e804-487f-aba0-3f32fc1afd5b

**Comment by Alex313031** [comment]
@lukeea12 Try the new #disable-aero flag that I added in the latest M119 release.

**Comment by lukeea12** [comment]
It's kinda fixed, now it happens randomly and for a few frames, but it's much less annoying than before.
Tested in the M120 release.

**Comment by lukeea12** [comment]
https://github.com/Alex313031/Thorium-Win/assets/147871385/1ce1fc7a-9737-4cce-b424-5f48acbccad9

example video. that new thing happens, and the decoloring thing (in the old video) still happen but very rarely.

**Comment by gz83** [comment]
What is your GPU model?  Are the drivers up to date?  In addition, if it is convenient, please check if there is any log information at the bottom of the chrome://gpu page.

**Comment by lukeea12** [comment]
gpu: nvidia gtx 1650 (4gb)
drivers: 551.23
log messages: GpuProcessHost: The info collection GPU process exited normally. Everything is okay. (idk if this is what you asked for exactly)

**Comment by Rairof** [comment]
This seems really similar to the issues I am facing in https://github.com/Alex313031/Thorium-Win/issues/167
Pretty sure its the Hardware acceleration being buggy in general as disabling it fixes these issues, this is also bad as hardware acceleration is important for various uses so I am hoping this is fined soon..

**Comment by lukeea12** [comment]
true, disabling hardware acceleration fixes the issue, but in my case, disabling it causes a pretty bad screen tearing so i cant use it comfortably.

**Comment by Rairof** [comment]
seems like it is fixed in latest 37th build as I am no longer experiencing those issues with hardware acceleration enabled now

**Comment by Rairof** [comment]
Seems like this issue still persists all be it its drastically minimal glitching now but it still exists
