### ISSUE TITLE
PLEASE CONTINUE THIS PROJECT❤️‍🔥

### ISSUE THREAD

**Issue by jiusiwu** [Alex313031/Thorium-Win#142]
**Add all the stuffz here**
You did a great job making this browser. This is the fastest browser for YouTube I've ever found. Please continue this project, it has been almost 3 months since the last update 😞

**Comment by gz83** [comment]
The project has not been abandoned and some new versions are currently being compiled

**Comment by Alex313031** [comment]
@jiusiwu The project is *not* dead. I was simply in the hospital for a month without access to a computer.
