### ISSUE TITLE
when is the real portable version? which leaves no garbage to the system and saves everything as cent

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [Alex313031/Thorium-Win#143]

**Comment by Alex313031** [comment]
@subsubsubsubsubsub I recently updated the portable .bat to also set the cache dir to the current dir. It shouldn't write anything outside the portable dir now (other than a few registry entries about where widevine is located, but this is not of concern)

**Comment by subsubsubsubsubsub** [comment]
![sshot-002](https://github.com/Alex313031/Thorium-Win/assets/73518754/2462db3b-3d9b-47cd-b85b-954b97bfe0dc)
Did I write correctly and how to transfer data but a new version?

**Comment by Alex313031** [comment]
@subsubsubsubsubsub You should refer to the .bat that is inside the latest M119 release. It has the --cache-dir flag set. But otherwise, your screenshot looks OK.

**Comment by subsubsubsubsubsub** [comment]
![sshot-001](https://github.com/Alex313031/Thorium-Win/assets/73518754/69183721-ffca-4b9f-a87c-69679365c3e6)??

add the main file to clear your browser cache. here is an example from the browser cent 

if "%~1"=="" (set "x=%~f0"& start "" /min "%comspec%" /v/c "!x!" any_word & exit /b)

RD /S /Q "%~dp0\User Data\Default\Cache"
RD /S /Q "%~dp0\User Data\Default\Code Cache"
RD /S /Q "%~dp0\User Data\Default\GPUCache"
RD /S /Q "%~dp0\User Data\Default\Session Storage"
RD /S /Q "%~dp0\User Data\Default\Service Worker\CacheStorage"
RD /S /Q "%~dp0\User Data\Default\Service Worker\ScriptCache"
RD /S /Q "%~dp0\User Data\Crashpad"
