### ISSUE TITLE
Is it possible to hide the gray line below the Thorium toolbar in dark mode? If so, how do I recompile it?

### ISSUE THREAD

**Issue by C1og** [Alex313031/Thorium-Win#144]
![image_1](https://github.com/Alex313031/Thorium-Win/assets/44397460/53e66d0c-3582-455b-9326-0afdb600609d)

like the new version of Edge browser:
![image](https://github.com/Alex313031/Thorium-Win/assets/44397460/8cfd0594-6f6c-4fd7-8924-c0340ee24d15)

**Comment by gz83** [comment]
This may be caused by the CR23 style. You can turn off the CR23 style in chrome://flags.

But as the Chromium browser development process advances, the CR23 style will become mainstream and completely replace the old interface style.

@C1og

**Comment by gz83** [comment]
Does Chromium 119 also have this line in the same configuration?

If Chromium 119 also has this line in the same configuration, then you won't need to spend time recompiling Thorium browser, which will not help in any way.

@C1og

**Comment by Alex313031** [comment]
@C1og @gz83 You can try disabling the new flag I added > chrome://flags/#force-enable-tab-outlines

**Comment by gz83** [comment]
This is not directly related to flags and should be a modification in the upstream.

@Alex313031
