### ISSUE TITLE
As thorium.bat put on the taskbar?

### ISSUE THREAD

**Issue by AlkBek** [Alex313031/Thorium-Win#145]
**System Details**
 - OS: [Windows  10 ]
 - Thorium Version [e.g. SE3 119.0.6045.214]

**Problem**
I opened thorium through thorium.bat and how do I put it on the taskbar now?

**Comment by Alex313031** [comment]
@AlkBek If you want it on the taskbar, why not just install it using the .exe?

If you really don't want to do that, go into the folder and right click thorium.exe, then click "create shortcut". Then you can rename the shortcut to remove the " - Shortcut" name at the end of it. Then you can drag-n-drop this shortcut onto the taskbar. batch files can sadly not be pinned to the task bar (although they *can* be manually added to the start menu by adding it in $userdatadir$)

**Comment by AlkBek** [comment]
@Alex313031 I'm just in thorium.bat has configured everything, and in thorium.exe I don't have anything set up, but come on.  Will -allow-outdated-plugins --disable-logging --disable-breakpad --disable-encryption --disable-machine-id work in thorium.exe ?

**Comment by GunGunGun** [comment]
> @Alex313031 I'm just in thorium.bat has configured everything, and in thorium.exe I don't have anything set up, but come on. Will -allow-outdated-plugins --disable-logging --disable-breakpad --disable-encryption --disable-machine-id work in thorium.exe ?

Just edit exe shortcut and add those to the shortcut, pretty much the same, shift and right click onto the thorium shortcut on Taskbar to show Properties ctx.
