### ISSUE TITLE
Batch file problem

### ISSUE THREAD

**Issue by Akaro5** [Alex313031/Thorium-Win#146]
**System Details**
 - OS: Windows 10 22h2 19045.3757
 - Thorium Version: Portable 119.0.6045.214

**Problem**
The batch file creates the folders "~dp0\USER_DATA\cache" and saves the data there.

**Screenshots**
![1](https://github.com/Alex313031/Thorium-Win/assets/115477405/2cbfb2ac-c542-4621-87b3-32e7408cc6ea)
![2](https://github.com/Alex313031/Thorium-Win/assets/115477405/d92d6582-14dc-46d2-a2cb-b910969a1e66)
![3](https://github.com/Alex313031/Thorium-Win/assets/115477405/42ef6d2f-cb80-4062-9e6c-f93c13822f17)

**Additional Notes**
When I delete "--disk-cache-dir="%~dp0%\USER_DATA\cache" all data saves in USER_DATA folder. Can this cause problems if I use it withous this? 
If I understand everything correctly, data should saves in USER_DATA folder, not in the "~dp0\USER_DATA\cache"

**Comment by Alex313031** [comment]
@Akaro5 Correct. Let me look into it. In the meantime, you can just remove that line if you dont care about thorium writing its cache to your system TEMP folder.

**Comment by Alex313031** [comment]
@Akaro5 Fixed, the goal was to prevent cache writes outside the dir, but it looks like it puts it in USER_DATA even without the flag, so I just removed it and reverted back to the way the .bat files were before. The lastest M120 release has this fix.
