### ISSUE TITLE
is there way to update to new thorium update without downloading the mini installer?

### ISSUE THREAD

**Issue by darkerraven** [Alex313031/Thorium-Win#147]
that is my question

**Comment by Itoktsnhc** [comment]
you can use scoop  https://github.com/epoweripione/scoop-bucket/blob/master/bucket/Thorium.json

**Comment by Alex313031** [comment]
@darkerraven Or the new https://github.com/Alex313031/thorium-winupdater

**Comment by darkerraven** [comment]
> @darkerraven Or the new https://github.com/Alex313031/thorium-winupdater

thank you!

**Comment by darkerraven** [comment]
> @darkerraven Or the new https://github.com/Alex313031/thorium-winupdater


@darkerraven Or the new https://github.com/Alex313031/thorium-winupdater

thank you!
