### ISSUE TITLE
Synchronization works very poorly

### ISSUE THREAD

**Issue by AlkBek** [Alex313031/Thorium-Win#149]
**System Details**
 - OS: [Windows 10]
 - Thorium Version [119.0.6045.214 (Официальная сборка) (64 бит) ]

**Problem**
After restarting, it logs out of almost all accounts. The password manager does not work, writes that it does not. Even if you import passwords, they will not be added.

**Screenshots**
![Synchonization](https://github.com/Alex313031/Thorium-Win/assets/126397035/8dcaa36c-91e8-4eb3-af9c-c1f8853e1e1f)
![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/613c4efa-8f46-4e38-aed3-94444e4f6f0f)

  **My flags**

![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/4eecb225-2bfe-4a7b-9ff4-31a874ffb92b)
![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/27d19b47-65bc-420b-9f9f-6c3c928bf164)
![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/b844ef9b-77f9-42a2-b795-8fa272b7a5a8)
![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/4c417c99-5e73-4cdd-a131-c485263950ce)
![image](https://github.com/Alex313031/Thorium-Win/assets/126397035/490fe05f-4048-45cd-bcef-8efeb2b30dad)

**Additional Notes**
It's in thorium.exe in thorium.bat everything works

**Comment by AlkBek** [comment]
I disabled #disable-encryption, #disable-machine-id and everything worked. And how to make sure that they are turned on and everything works?

**Comment by jestxfot** [comment]
https://github.com/Alex313031/Thorium-Win/issues/150

**Comment by Alex313031** [comment]
@jestxfot @AlkBek Yeah what jestfox said lol.
