### ISSUE TITLE
Impossible to move in the youtube video

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win#15]
Hello, it is impossible to move in the video, I can't advance 10 seconds in the video

 https://www.youtube.com/watch?v=7a1CXzxnFHw&t=5s

**Comment by trimechee** [comment]
I use Thorium avx2, even live youtube video doesn't work yesterday, i precise i can play other youtube videoS but it seems there is some youtube video et and live youtube , Thorium can't play them

**Comment by trimechee** [comment]
Finally i restart windows and i can play and move in this video

**Comment by tomByrer** [comment]
> Finally i restart windows and i can play and move in this video

Youtube has been strange for me for the past few weeks on many different browsers.  I think they keep tweaking the code on their end.

**Comment by trimechee** [comment]
It's bizarre, few days ago, in the settings of youtube, there was option to enable or disable AV1 codec, now this option disappear , i use edge browser....if there is problem, we hope it will be fixed in youtube , microsoft edge browser has migrate to chromium engine after youtube playback problems....

**Comment by Alex313031** [comment]
@tomByrer @trimechee Yeah, I dont think this is a thorium problem, but a youtube problem.
