### ISSUE TITLE
Hi! Can you please update the Windows AVX2 build to a newer one? Thanks!

### ISSUE THREAD

**Issue by kepler2** [Alex313031/Thorium-Win#152]
HI and I hope you are doing well!

Thanks again for this great project!

Is there any way you can update the Windows builds (AVX2)?

https://github.com/Alex313031/Thorium-Win-AVX2

This is 2 weeks old :(.

Thanks!

**Comment by wmgaertner** [comment]
All the windows builds are being released under this repo now, you can find the avx2 version in the M120 release.

**Comment by Alex313031** [comment]
@kepler2 Yeah, what @wmgaertner said lol.
