### ISSUE TITLE
Excessively complex process to download a Windows build... time to touch grass...

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Alex313031/Thorium-Win#154]
I visit the website [https://thorium.rocks/](https://thorium.rocks/), and when I click on the Windows section, I find three different .exe files available for download. It's confusing to determine which one is the standard download. For the average user like me, terms like AVX2, SSE3, and AVX are unfamiliar and don't make sense. People generally aren't familiar with terms like ARM either. It would be helpful to have a clear indication of the regular download option for users who may not be tech-savvy.

Also, is mini installer the same as portable? Seems like it's the same as unzipping a .zip file and clicking a .exe

Just all over the place... don't worry, I'll find the door.

p.s. BTW. Great job on the releases and appreciate the dev, cheers.

**Comment by eltrevii** [comment]
> AVX2 (also known as Haswell New Instructions) expands most integer commands to 256 bits and introduces new instructions. They were first supported by Intel with the [Haswell](https://en.wikipedia.org/wiki/Haswell_(microarchitecture)) processor, which shipped in 2013.

[source](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions)
so yeah use avx2 its far better
and im guessing the mini is only for the installer. i dont know a lot about this but i suppose its a mini installer for the normal version of thorium or something but again i dont know

**Comment by jestxfot** [comment]
I think Alex made the right move to merge all windows versions into one repository, it is very hard to keep track of 3 repositories and problems are spread out between them. For such options it is better to use branches of course.

I hope that in the future all windows versions will be combined into one release

**Comment by eltrevii** [comment]
> I hope that in the future all windows versions will be combined into one release

actually its not good; the problem with this is that avx2 may not be supported in some older operating systems or cpus and the same goes for sse3 etc so i think its better to give people the fatest option for their system and also options that are compatible with older systems

**Comment by grand-lotus-iroh** [comment]
I appreciate the available choices, and I have a suggestion. It would be beneficial to include a **(recommended)** label next to the downloadable build that you believe will be the most popular or suitable. This way, newcomers can easily join the Thorium fanbase without frustration. Instead, they'll be delighted to explore something truly excellent, allowing them to appreciate the dedicated hard work and development behind Thorium.

**Comment by grand-lotus-iroh** [comment]
I understand your perspective, but by making an educated guess, one
could deduce it's an AMD64 architecture, also known as x86-64 or simply
x64, given that those CPU make up a significant portion, potentially
between 50% to 80%, of the worldwide computer supply. This is why I
suggested incorporating a recommended label. My focus is on enhancing
the project for end-users, and the current setup is, in my opinion, not
acceptable.

You mentioned "users can have older or newer systems"
Just a heads up, "pre x86" was late 1980s and early 1990s…
Hey, do your thing and Happy Thursday and thanks for the excellent
contribution. I've installed it across multiple operating systems and it
seems to only get faster and faster the more I use it.


On February 1, 2024, Daniele Rolli ***@***.***> wrote:
> @grand-lotus-iroh <https://github.com/grand-lotus-iroh> the problem is
> that we dont know what kind of computer the end user has, so there is
> no way to actually determine what version will be best because users
> can have older or newer systems
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Alex313031/Thorium-Win/issues/154#issuecomment-
1921846312>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAJ3IZEF7426BTQRMA4XDDDYRPGJ7AVCNFSM6AAAAABCJODJH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMRRHA2DMMZRGI>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by eltrevii** [comment]
no no i dont mean x86, my point is that some cpus dont support avx2 which has nothing to do with x86

**Comment by jestxfot** [comment]
I don't think this will make it too difficult for users. Just specify approximate years of supported processes based on AVX technology. Besides, the user can always try several options, it's not that big a problem.

It would be much more inconvenient for the user if the installers were in different repositories.
