### ISSUE TITLE
Instagram reels not working

### ISSUE THREAD

**Issue by Overpricedgpu** [Alex313031/Thorium-Win#159]
Everything working fine except reels in instagram, tab goes unresponsive everytime.
![image](https://github.com/Alex313031/Thorium-Win/assets/114041735/bfb65a92-6d5e-4e22-9812-c26c95dd2b01)
![image](https://github.com/Alex313031/Thorium-Win/assets/114041735/ad671b28-bf63-455a-a701-e7a13b2aecc6)

Sometimes it come back after 3-4 reels it stops responding.

**Comment by Rafi1018** [comment]
Having somewhat same problem. It lags while browsing videos on youtube or facebook. Felt like it had some issues with gpu drivers (not sure) I'm using AMD & using the latest AVX2 mini installer

**Comment by Overpricedgpu** [comment]
> Having somewhat same problem. It lags while browsing videos on youtube or facebook. Felt like it had some issues with gpu drivers (not sure) I'm using AMD & using the latest AVX2 mini installer

I have a intel laptop with nvidia mobile gpu. I have tried brave and opera but same issue. Maybe it's a hardwere issue then.

**Comment by Rafi1018** [comment]
> > Having somewhat same problem. It lags while browsing videos on youtube or facebook. Felt like it had some issues with gpu drivers (not sure) I'm using AMD & using the latest AVX2 mini installer
> 
> I have a intel laptop with nvidia mobile gpu. I have tried brave and opera but same issue. Maybe it's a hardwere issue then.

yeah might be a driver issue
