### ISSUE TITLE
Unable to stream max or peacock

### ISSUE THREAD

**Issue by Dragoon4935** [Alex313031/Thorium-Win#164]
**System Details**
 - OS: windows 11
 - Thorium Version Version 120.0.6099.235 (Official Build) (64-bit)

**Problem**
When attempting to stream both peacock and HBO max, both error at stating we are unable to stream, works fine in other chrome broswers

**Comment by hapnan** [comment]
this may be due to drm problems, for more details please check this is issues #73

**Comment by Alex313031** [comment]
@hapnan @Dragoon4935 Yup. It's out of my control.
