### ISSUE TITLE
AVX2 vs AVX vs SSE3 which one to pick?

### ISSUE THREAD

**Issue by Rafi1018** [Alex313031/Thorium-Win#166]
My hardware supports all. So was thinking what would be better?
I know AVX2 is better but was thinking if it has any drawbacks

**Comment by etil2jz** [comment]
You can take AVX2, the only drawback I can see is slightly more CPU temp while using these instructions but it's negligeable.

**Comment by Rafi1018** [comment]
> You can take AVX2, the only drawback I can see is slightly more CPU temp while using these instructions but it's negligeable.

gotcha thanks for your opinion!

**Comment by AJolly** [comment]
Any benchmarks on this?  Lets assume I've got a 14900ks
