### ISSUE TITLE
Now, the performance of Thorium is actually inferior to Chrome.

### ISSUE THREAD

**Issue by Malus-risus** [Alex313031/Thorium-Win#168]
**Now, the performance of Thorium is actually inferior to Chrome.**

The test versions are Thorium (AVX2) 121.0.6167.204 and Chrome 121.0.6167.185. Thorium scored 181 on Speedometer 2.1, while Chrome scored 127. After six rounds of testing, the results varied significantly.
The reason for raising this issue is that Thorium originally boasted that its performance would be significantly higher than Chrome's, but now the situation has reversed. I hope the developers will take this issue seriously and make improvements. Thank you!

**Comment by gz83** [comment]
You should run the browser performance test in incognito mode and close all background programs. The picture below is my test result. I don't know why you got such a low result value.

Also, if possible, you need to provide the URL of the website where you tested the browser's performance.

![image](https://github.com/Alex313031/Thorium-Win/assets/17492865/87850e6d-0e93-469e-b072-211dc2089b2e)

@Malus-risus

**Comment by Malus-risus** [comment]
> You should run the browser performance test in incognito mode and close all background programs. The picture below is my test result. I don't know why you got such a low result value.
> 
> Also, if possible, you need to provide the URL of the website where you tested the browser's performance.
> 
> ![image](https://private-user-images.githubusercontent.com/17492865/306172095-87850e6d-0e93-469e-b072-211dc2089b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjgxMzgsIm5iZiI6MTcwODQyNzgzOCwicGF0aCI6Ii8xNzQ5Mjg2NS8zMDYxNzIwOTUtODc4NTBlNmQtMGU5My00NjllLWIwNzItMjExZGMyMDg5YjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDExMTcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZmFiZWFjOTI2MDJjOWNhZWFjZDY2Y2I0MDEzMDFiYWRhOGFmMDIwNmUyOGVhODY1YjQ0NmE0NDQyNDViM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JhCSZVlVkUdlCc6IdKsMF9XDd1p1RuAMF8TZXaRJ0Rc)
> 
> @Malus-risus

![image](https://github.com/Alex313031/Thorium-Win/assets/69906215/de628682-d2f6-4d90-aa40-c3eaeb4aab3e)
it is thorium



![image](https://github.com/Alex313031/Thorium-Win/assets/69906215/e4722097-174a-4ac4-913f-f4d185bcecb6)
it is chrome

**Comment by Malus-risus** [comment]
> Can you send me the URL of Speedometer?
> 
> Also, what are your computer’s monitor refresh rate, resolution, and browser zoom ratio?
> 
> @Malus-risus

https://browserbench.org/Speedometer2.1/

60hz refresh rate，1080p 100%zoom ratio

**Comment by gz83** [comment]
I still got higher results than yours. In addition, browser performance varies from person to person, so you shouldn’t get too hung up on this issue.

![Snipaste_2024-02-20_22-14-35](https://github.com/Alex313031/Thorium-Win/assets/17492865/13bb979c-4ced-46f0-a9fb-4f59b951db74)
![Snipaste_2024-02-20_22-15-02](https://github.com/Alex313031/Thorium-Win/assets/17492865/9e91d7e7-970e-47af-9f71-a899d9c30dba)
![Snipaste_2024-02-20_22-15-19](https://github.com/Alex313031/Thorium-Win/assets/17492865/1ab8ae1d-6dbe-4fd2-9999-e57bd044cebb)

@Malus-risus

**Comment by Malus-risus** [comment]
> I still got higher results than yours. In addition, browser performance varies from person to person, so you shouldn’t get too hung up on this issue.
> 
> ![Snipaste_2024-02-20_22-14-35](https://private-user-images.githubusercontent.com/17492865/306293995-13bb979c-4ced-46f0-a9fb-4f59b951db74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzkwODcsIm5iZiI6MTcwODQzODc4NywicGF0aCI6Ii8xNzQ5Mjg2NS8zMDYyOTM5OTUtMTNiYjk3OWMtNGNlZC00NmYwLWE5ZmItNGY1OWI5NTFkYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMWYxNmU3YzU3MmUzYmEwNDVlYmQzNDczNWQwZmYwMGI5ODA4MzY3ZTc5ZWI2MWNlOTEwYTg3YWEwOTk4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fGD_UDHiDME2EYjJEeHWnGHwzudXUP8M7UlCRC0Er4) ![Snipaste_2024-02-20_22-15-02](https://private-user-images.githubusercontent.com/17492865/306294001-9e91d7e7-970e-47af-9f71-a899d9c30dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzkwODcsIm5iZiI6MTcwODQzODc4NywicGF0aCI6Ii8xNzQ5Mjg2NS8zMDYyOTQwMDEtOWU5MWQ3ZTctOTcwZS00N2FmLTlmNzEtYTg5OWQ5YzMwZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODcyM2E5MGM1YTcwMmUyMWIxMzJmNTcyZjJhMDhjNzgxNDMyNzI3YWUyMGY5NjhhZjAwYWY1OTQwOTBhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AqI7ypDc-gmkOPg7yEYDv1zr7Ga9It0rdzbTHrZdJpw) ![Snipaste_2024-02-20_22-15-19](https://private-user-images.githubusercontent.com/17492865/306294007-1ab8ae1d-6dbe-4fd2-9999-e57bd044cebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzkwODcsIm5iZiI6MTcwODQzODc4NywicGF0aCI6Ii8xNzQ5Mjg2NS8zMDYyOTQwMDctMWFiOGFlMWQtNmRiZS00ZmQyLTk5OTktZTU3YmQwNDRjZWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0MTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YzlhNTNjNWNmMDFiZDgyMGNlNDQ3NGMzN2NhOTAwN2ZmOTY1NzQwZThkOTYxMWJmODhmOWM3NzBjYjI1ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rSllbH5WvqtgSndrmI7QCexzNRCrGBLtVwe-YCLIjFQ)
> 
> @Malus-risus

my cpu is i3 10100f.It's surprising that the performance is actually worse than Chrome, and by a considerable margin.

**Comment by gz83** [comment]
I'm using an Intel i7-13700HX processor, also, I see some repos under your account that are mainly in Simplified Chinese as well as repos that bypass the network restrictions, from which I conclude that you're most likely from mainland China, and I think that the network may also have an impact on the performance test results, but I have no clear evidence of this.

@Malus-risus

**Comment by Malus-risus** [comment]
> I'm using an Intel i7-13700HX processor, also, I see some repos under your account that are mainly in Simplified Chinese as well as repos that bypass the network restrictions, from which I conclude that you're most likely from mainland China, and I think that the network may also have an impact on the performance test results, but I have no clear evidence of this.
> 
> @Malus-risus

Have you tried running Chrome on your device for a test? What were the scores like?

**Comment by gz83** [comment]
![Snipaste_2024-02-20_23-06-05](https://github.com/Alex313031/Thorium-Win/assets/17492865/e9fcc06f-104c-4783-b88f-cab104f7c148)

419 points

@Malus-risus

**Comment by midzer** [comment]
>  think that the network may also have an impact on the performance test results, but I have no clear evidence of this.

Speedometer 2.1 JavaScript assets are cached in browser after they've all been downloaded.

When I run the test (incognito with no extensions, no background tasks, fresh reboot), I restart test after first ~45 steps are through.

-> This way, I ensure no network connections are involved in the benchmark.

**Comment by gz83** [comment]
Thanks for the information provided by midzer

@midzer

**Comment by midzer** [comment]
Further thoughts:

Just incase Thorium *really* can't compete or is equal in terms of performance to regular Chrom* browsers, we could discuss whether Thorium still deserves the headline "the fastest browser on earth". How about "the cutest browser on earth"?

An update on https://thorium.rocks/performance would be nice, too @Alex313031

**Comment by People-11** [comment]
From Chrome 114, google uses Maglev compiler that brings huge performance improvement. It's comparable to the optimization done by Thorium. 

But now Throium is an ease-of-use improvement for me, like I can right-click directly on the refresh button in order to choose to force a refresh. It removes most of Google's bloatware but still keeps sync. Also adds a lot of useful patches. For me, it's still better than the original.

**Comment by chaoscreater** [comment]
There's barely any info provided, how is anyone supposed to measure this properly? 

How do we know you're comparing apples to apples? When you run the speedometer test, it will increase your browser's RAM usage by about 2GB. If your Thorium has a bunch of active tabs open and is already using e.g. 5GB of RAM and you run this test, and you compare this to Chrome with no tabs open and running at like 800MB of RAM, then it's not going to give you an accurate performance measure. 

What extensions do you have installed on both? Are they equal? Some extensions like Noscript can interfere with elements on a webpage, let alone performance benchmark tests.

Also, Thorium is actually portable with the encryption able to be disabled, whereas Chrome isn't. Good luck taking your profile across to a new PC when you need to migrate. It's not just the performance that you should be looking at.

**Comment by GHOST-DEKU** [comment]
> > There's barely any info provided, how is anyone supposed to measure this properly?
> > How do we know you're comparing apples to apples? When you run the speedometer test, it will increase your browser's RAM usage by about 2GB. If your Thorium has a bunch of active tabs open and is already using e.g. 5GB of RAM and you run this test, and you compare this to Chrome with no tabs open and running at like 800MB of RAM, then it's not going to give you an accurate performance measure.
> > What extensions do you have installed on both? Are they equal? Some extensions like Noscript can interfere with elements on a webpage, let alone performance benchmark tests.
> > Also, Thorium is actually portable with the encryption able to be disabled, whereas Chrome isn't. Good luck taking your profile across to a new PC when you need to migrate. It's not just the performance that you should be looking at.
> 
> I ran it with all tabs and extensions closed, and no other software was running on the computer. Moreover, I believe that even if its performance isn't as good as Chrome's, I would continue to use it, as Thorium's advantages are not limited to just this.
I don't see any other benefit of thorium over chrome, except that it is open-source
