### ISSUE TITLE
Off topic: tips for building computer?

### ISSUE THREAD

**Issue by tomByrer** [Alex313031/Thorium-Win#17]
Any thoughts about building hardware to build Chrome/Thorium?  How long does it take for you to build?  Think more than 32Gb RAM is useful?
TIA

**Comment by Alex313031** [comment]
@tomByrer I am using a fairly old system. A FX-8370 overclocked to 4.6Ghz, 24GB DDR3 1866Mhz, and a 1TB SSD. For me, compiling thorium takes 4-6 hours. @gz83 Is using a server with a 11th gen core i7, and 16GB ram, and SSD, and it takes him 2-3 hours.

You will need at a minimum: 2 core processor, 8GB ram, and 75 GB free space. Having 16 or more gb ram is better. 32 is overkill and wont make it faster. The newer/more cores/larger cache/higher frequency your CPU is, the better. This is the main limiting factor.

Someone used a Ryzen Threadripper 3990X overclocked to 4.2GHz on all cores, and compiled Chromium in 20 minutes lol

**Comment by Alex313031** [comment]
@tomByrer Also, this isnt off topic at all. Stuff like this is welcome, and I like when people post issues asking about building Thorium, it makes me happy that people want to build my project. I am also open to having a one on one with anyone on any social media platform, to guide them through anything they need help on. I am usually free.

**Comment by tomByrer** [comment]
I just picked up an Core i5-12600K, 64Gb of DDR4 3600 cl16 RAM... Maybe I'll make a RAM-disk since I will use old SSD?

**Comment by Alex313031** [comment]
@tomByrer That should be more than enough to build Thorium/Chromium in 4 hours or less. And no need to make a ram disk, an SSD, even an old one, will perform superbly for building. IDK if you got the idea for making a ram disk from the official linux building instructions, but that section in the doc is out of date, and was intended for people building with a regular HDD.

**Comment by Alex313031** [comment]
@tomByrer Are you intending to build thorium? if so, for what platform?

If you have any issues or questions regarding the building process for either thorium or chromium, dont hesitate to make an issue. I also can have a one on one with you on pretty much anything. I have facebook, instagram, snapchat, phone number, telegram, there is the new Thorium IIRC chat, etc. Only thing i dont have is microsoft teams or discord

**Comment by Alex313031** [comment]
@tomByrer Hi. Checking back in. Hows it going. Have you made any chromium or thorium builds. If you made a chromium build, did you use some or all of thoriums args.gn?
