### ISSUE TITLE
Can't open any version of the browser

### ISSUE THREAD

**Issue by Mason-17** [Alex313031/Thorium-Win#176]
**System Details**
 - OS: Windows 11
 - Thorium Version : All of them

**Problem**
After installing (any) version of thorium browser after attempting to update to the latest version, i can no longer run thorium browser. the App simply doesn't open.

**Screenshots**
[None]

**Additional Notes**

**Comment by Cary2060** [comment]
Same, just add a short cut to any website, for some reason the main icon just closes the application.

**Comment by Pouppa2020** [comment]
Yeah same here. I deleted everything and tried every single version .exe and .zip nothing works. This sucks,

**Comment by aydinunal** [comment]
same...it does not start with the shotcut,  exe file starts but even with the correct arguments there is a problem with theprofiles. I think in my case the problem is closely related with the second profile.

**Comment by godenk789** [comment]
Add flag `--profile-directory="default"` to the thorium shortcut, it works for me

**Comment by Cary2060** [comment]
> Add flag `--profile-directory="default"` to the thorium shortcut, it works for me

where do you add this at?

**Comment by godenk789** [comment]
> > Add flag `--profile-directory="default"` to the thorium shortcut, it works for me
> 
> where do you add this at?

Right click thorium shortcut > Properties.
In the target column, add the flag after "thorium.exe"
Example:
Target: `C:\Users\yourusername\AppData\Local\Thorium\Application\thorium.exe --profile-directory="default"`

**Comment by Alex313031** [comment]
@aydinunal @Cary2060 @godenk789 @Mason-17 @Pouppa2020 Fixed in latest M122 version.
