### ISSUE TITLE
Add support to Twitch login

### ISSUE THREAD

**Issue by Medrantol** [Alex313031/Thorium-Win#183]
When I try to login to Twitch I get this error:

![mstsc_2024-03-08_13-45-15](https://github.com/Alex313031/Thorium-Win/assets/162044550/42ece31d-2cc3-4839-b7e9-f6628e360369)

I edited the user agent but got the same error. Incognito with no extensions same.
Can we add support to this site? I have no problems with Brave or Chrome.
edit: tried a clean install, same error.

I'm using **Thorium-Win-AVX2**
Version 119.0.6045.214 (Official Build) (64-bit)
edit: same error with Thorium_WIN32_SSE3_119.0.6045.214

**Comment by Medrantol** [comment]
Even when it failed after a trying with a fresh install, the problem was solved after getting the error and clearing the site cookies. I don't really understand that logic, but it works ¯\_(ツ)_/¯.

**Comment by Xzero3007** [comment]
Same error. Suddenly since today. clearing cookies did not help. What can I do?
