### ISSUE TITLE
Bitdefender Blocks my installation of Thorion verison 123

### ISSUE THREAD

**Issue by IkimonJ** [Alex313031/Thorium-Win#203]
**System Details**
 - OS: Windows 10 Version 22H2
 - Thorium Version M123.0.6312.133

**Problem**
Bitdefender stops my installation when installing Thorium M123.0.6312.133

**Screenshots**
![Screenshot_770](https://github.com/Alex313031/Thorium-Win/assets/102239906/c2f6de0a-7fd2-405e-8988-cfbdac7c076c)

**Comment by gz83** [comment]
#195
