### ISSUE TITLE
Multi user install

### ISSUE THREAD

**Issue by MidyGamy** [Alex313031/Thorium-Win#206]
The installer curently install Thorium for the curent user using it, but what if we want to install it for the whole machine (kinda base Google Chrome)... I it possible to have an option to do so?

I'm often switching between my onw user and Windows built-in administrator user so I'd prefer have only 1 global instalation instead of 1 per user

**Comment by gz83** [comment]
Try passing the --system-level parameter to mini_installer

**Comment by MidyGamy** [comment]
Let me try
