### ISSUE TITLE
The files "notification_helper.exe" and "chrome_proxy.exe" flagged by Windows Defender in latest build

### ISSUE THREAD

**Issue by Girofox** [Alex313031/Thorium-Win#211]
**System Details**
 - OS: Windows 11
 - Thorium Version M123.0.6312.133

**Problem**

The executable files
- `Thorium_WIN\BIN\123.0.6312.133\notification_helper.exe`
- `Thorium_WIN\BIN\chrome_proxy.exe`

are flagged by Windows Defender as `Trojan:Win32/Znyonm` and `Trojan:Win32/Acll` respectively. This didn't happen before.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/43116061/8bb93829-56cc-4840-9956-b8484ab36cbf)
![image](https://github.com/Alex313031/Thorium-Win/assets/43116061/7fce4a13-28c6-4ed6-a266-aef36f0fdcf7)

**Comment by gz83** [comment]
Duplicate
