### ISSUE TITLE
Bitdefender detected gen:variant.lazy.521198

### ISSUE THREAD

**Issue by UrsUbigfoot** [Alex313031/Thorium-Win#212]
**System Details**
 - OS: Windows 11 Pro 22H2 22621.3447
 - Thorium Version 122.0.6261.132

**Problem**
Wanted to install the new version of Thorium 123.0.6312.133 and bitdefender detected malware gen:variant.lazy.521198
![Thorium malware](https://github.com/Alex313031/Thorium-Win/assets/16020316/80d64497-3e6e-43a6-b3da-973b93f0c0c4)

**Comment by gz83** [comment]
Duplicate
