### ISSUE TITLE
Serious Issue with DATA Folder not being Recognized!!!

### ISSUE THREAD

**Issue by adsactly** [Alex313031/Thorium-Win#213]
**System Details**
 - OS: Windows 10
 - Thorium Version Thorium_SSE3_122.0.6261.132 upgraded to Thorium_SSE3_123.0.6312.133

**Problem**
I have already submitted this bug in the main Thorium Thread for issues but I think this where I should let the community know about this serious issue. All I did was download and unzip the new Portable and Copied the BIN and Thorum.BAT to the the new updated folder and NOW my Profile is not coming up only my bookmarks not my extensions which are much more important and even urgent! 

**Screenshots**

**Additional Notes**

**Comment by gz83** [comment]
duplicate
