### ISSUE TITLE
Extension Icon on menu bar not changing with colour

### ISSUE THREAD

**Issue by TeitokuIppan** [Alex313031/Thorium-Win#214]
**System Details**
 - OS: Windows 11 Pro
 - Thorium Version 123.0.6312.133

**Problem**
The Extensions icon on both the old UI and the Refresh 2023 UI menu bars do not have the Thorium blue colour disabled even when #disable-thorium-icons is set to 'Enabled', therefore it clashes with every theme that isn't blue as it's colour scheme.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/11202928/b431d09f-39de-455b-90b2-c6334fcba3d1)
![image](https://github.com/Alex313031/Thorium-Win/assets/11202928/22faedb6-4b80-44c8-a44d-a66e5ab8e744)

**Comment by gz83** [comment]
duplicate
