### ISSUE TITLE
question : Any way to remove Hangouts and PDF viewer extensions.

### ISSUE THREAD

**Issue by Vipin2003** [Alex313031/Thorium-Win#216]
Isn't there any way to remove these extensions from Thorium. It is known that thorium provides all features of chrome bcoz of which these extensions are there. But most of the people like me like to use adobe instead of Thorium (Chrome). So, People like me don't want extra extensions. There should be a option to remove them. OR if the option exits, then help me with the guide to remove them. Thanks

**Comment by gz83** [comment]
This is a built-in extension and it exists in Chrome as well, we just managed to show it. Also, this question has been answered many times.

**Comment by Vipin2003** [comment]
> This is a built-in extension and it exists in Chrome as well, we just managed to show it. Also, this question has been answered many times.

Then, why don't you hide them....Isn't there any way in thorium to hide them.? Like some flag which you can introduce?

**Comment by gz83** [comment]
Hiding these extensions does not mean deleting them. You can also allow Acrobat to open PDF files by changing the file association.

We expose them to the public at the source code level, and users cannot hide them at the moment.

**Comment by JoachimHenze** [comment]
It's a misery that google did not do that more plugin-like. So that unwanted stuff could be stripped entirely.

**Comment by Alex313031** [comment]
You would not want to get rid of the PDF viewer. Without it, PDFs cannot be displayed or printed from. Every Chromium based browser has this, but it is normally hidden. The hangouts extension is optional, and can be configured at build time with the `enable_hangout_services_extension = true/false` argument. Most, but not all, Chromium based browsers have this, and again it is normally hidden. This extension is only used on Google Hangout websites, and requires the user to consent to microphone/camera before it is ever actually activated.

**Comment by Vipin2003** [comment]
> You would not want to get rid of the PDF viewer. Without it, PDFs cannot be displayed or printed from. Every Chromium based browser has this, but it is normally hidden. The hangouts extension is optional, and can be configured at build time with the `enable_hangout_services_extension = true/false` argument. Most, but not all, Chromium based browsers have this, and again it is normally hidden. This extension is only used on Google Hangout websites, and requires the user to consent to microphone/camera before it is ever actually activated.

So, can't you directly implement a flag which triggers this argument. Like you did with your icons too.

**Comment by Alex313031** [comment]
@Vipin2003 I mean I probably could, but it means more work. Why are you so concerned about it?

You can view the source here, and see that there is nothing malicious > https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/hangout_services/

**Comment by Vipin2003** [comment]
> @Vipin2003 I mean I probably could, but it means more work. Why are you so concerned about it?
> 
> You can view the source here, and see that there is nothing malicious > https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/hangout_services/

Try to do it when you are free or have time. I'm just asking other's people concern.

**Comment by Vipin2003** [comment]
Reflected in [M124.0.6367.218 - 40th Release](https://github.com/Alex313031/Thorium-Win/releases/tag/M124.0.6367.218).
Thanks to dev for listening to audience

**Comment by gz83** [comment]
Once again, the flag introduced this time only hides these extensions, but does not delete them.
