### ISSUE TITLE
Unable to access vpn.klikbca.com using 1.1.1.1

### ISSUE THREAD

**Issue by gnulab-id** [Alex313031/Thorium-Win#222]
**System Details**
 - OS: Windows 11
 - Thorium Version 123.0.6312.133

**Problem**
Under setting, I set Secure DNS provider is cloudflare. One day I cannot access the website vpn.klikbca.com anymore unless I set it to Google DNS.

I tried the same setting using Chromium, I can access it. So does using Firefox.

Sometimes it throws this error message ERR_NAME_NOT_RESOLVED

Sometimes it just shows white blank page.

How do I troubleshoot this?

Henry

**Comment by daniilpankrashin** [comment]
```
ping -4 vpn.klikbca.com -n 1
```

```
Pinging vpn.nsec.klikbca.com [202.6.208.46] with 32 bytes of data:
Request timed out.

Ping statistics for 202.6.208.46:
    Packets: Sent = 1, Received = 0, Lost = 1 (100% loss),
```

The website you are trying to access times out, it is not an issue within thorium or cloudflare DNS.

**Comment by hapnan** [comment]
vpn.klikbca.com in my browser work fine, try doing a flushdns maybe it will work again

**Comment by gnulab-id** [comment]
And today everything works when I had not done anything.
