### ISSUE TITLE
Chrome Refresh UI Not working in M124.0.6367.218 - 40th Release

### ISSUE THREAD

**Issue by aidenszolosi** [Alex313031/Thorium-Win#223]
**System Details**
 - OS: Windows 11
 - Thorium Version M124.0.6367.218

**Problem**
Chrome Refresh UI Not working despite being enabled in chrome://flags and in the labs icon in the top right.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/68137338/d574c609-3251-4f65-bd1f-c248ad73c44d)**Additional Notes**

This could also just be that the UI has changed to be much more compact and alike the beforehand; however, I don't think this is an intended feature. 
Thanks!

**Comment by rohitsaha29** [comment]
System Details

OS: Windows 11
Thorium Version M124.0.6367.218

Side panel completely bugged and broken with red on top of the Chrome Refresh not working


![image](https://github.com/Alex313031/Thorium-Win/assets/89363390/53bb6845-2ea7-4e49-bbb9-e318c781a66a)

**Comment by aidenszolosi** [comment]
> System Details
> 
> OS: Windows 11 Thorium Version M124.0.6367.218
> 
> Side panel completely bugged and broken with red on top of the Chrome Refresh not working
> 
> ![image](https://private-user-images.githubusercontent.com/89363390/331681541-53bb6845-2ea7-4e49-bbb9-e318c781a66a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzYwNzAsIm5iZiI6MTcxNTk3NTc3MCwicGF0aCI6Ii84OTM2MzM5MC8zMzE2ODE1NDEtNTNiYjY4NDUtMmVhNy00ZTQ5LWJiYjktZTMxOGM3ODFhNjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE5NTYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1YzExNDliMWEzNWRiNTE0NmRmZDkzYTE0OTBmZTVkODE5NTYxODU3MGZkMGQ0Yjc5MWFmMjhiYjdmMjUwZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7v8aQsIQZrt_Tr6EWyC7B-Zmmb8kmMI5FZBywB2VDgc)

Thank you for this addition. I noticed this as well and stupidly forgot to add it! You're awesome, thank you!

**Comment by mjivraja** [comment]
I have the same issue in Linux. Web Refresh is not working.

**Comment by AmizRm** [comment]
`--disable-features=CustomizeChromeSidePanelNoChromeRefresh2023`

You will need to specify it manually on the commandline, either from the terminal, or to make it permanent, by editing the shortcut (on Windows), or editing /usr/bin/thorium-browser (on Linux). Next release will fix this.

**Comment by aidenszolosi** [comment]
> `--disable-features=CustomizeChromeSidePanelNoChromeRefresh2023`
> 
> You will need to specify it manually on the commandline, either from the terminal, or to make it permanent, by editing the shortcut (on Windows), or editing /usr/bin/thorium-browser (on Linux). Next release will fix this.

Can confirm this workaround works.

**Comment by fmitesh007** [comment]
i got the same issuee

**Comment by daikisoul** [comment]
just asking when is it going to be fixed?

**Comment by aidenszolosi** [comment]
> just asking, when is it going to be fixed?

atp who knows. he used to update it like biweekly at least to update the chromium version but it hasn't been updated in quite a bit. For now, It's probably better to switch to a different browser that has the latest chromium versions or at least updates it more often. When an update rolls out I"ll be coming back but for now I dislike all of the bugs present and the outdated chromium version (which effects extensions like 1password)
