### ISSUE TITLE
YOUTUBE : The following content is not available on this app. Watch on the latest version of YouTube. Learn more

### ISSUE THREAD

**Issue by oxinsstyle** [Alex313031/Thorium-Win#226]
**System Details**
 - OS: Windows 11 23H2 Build: 22631.3672]
 - Thorium Version 124.0.6367.218

**Problem**
YOUTUBE : The following content is not available on this app. Watch on the latest version of YouTube. Learn more
https://www.youtube.com/watch?v=7uuypza4UZ0

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/99094515/6a93bd60-c139-412f-9dcd-0da8603fc7a4)

**Additional Notes**
this also applies on Microsoft Edge Version 125.0.2535.85 (Official build) (64-bit)
also in incognito [ Thorium & Microsoft Edge  ]

**Comment by gz83** [comment]
Are you using dPWA?

**Comment by oxinsstyle** [comment]
> Are you using dPWA?

can you explain me what that exact is?

**Comment by gz83** [comment]
https://support.google.com/chrome/answer/9658361?sjid=15568418238459452469-AP&co=GENIE.Platform%3DDesktop&oco=0
