### ISSUE TITLE
Thorium is not a valid Win32 application

### ISSUE THREAD

**Issue by rw5207** [Alex313031/Thorium-Win#228]
**System Details**
 - OS: Windows 7 Ultimate 6.1.7601 Service Pack 1 Build 7601
 - Currently running Thorium 122.0.6261.168 (Official Build) (32-bit)

**Problem**
Trying to upgrade to 124.0.6367.218

**Screenshots**

**Additional Notes**
Running an i3-2120 on a Dell Optiplex 390 that is supposed to support Intel® SSE4.1, Intel® SSE4.2, Intel® AVX.  Every new version I download and try to run throws the "Thorium.exe is not a valid Win32 application" error.    If I download the mini installer I get the same error.

**Comment by gz83** [comment]
The version in this repo does not support your system. Please use the version in the thorium-legacy repo
