### ISSUE TITLE
Page crashes (home assistant)

### ISSUE THREAD

**Issue by Werewolfke** [Alex313031/Thorium-Win#230]
On windows 11, installed with the thorium_AVX2_mini_installer.exe
I cant open up my home assistant dashboard, because it crashes after it loads.
It sometimes recovers, i think its because of graphs and or animations.
It crashes before loading set items, and if it recovers, it shows those items, but after a few seconds the page becomes unresponsive again.

It works on Chrome, Firefox, Floorp (firefox like), 
Works also on Thorium on android, and chrome, and Iceraven (android firefox like).

Could this be because of a non-default flag? i tried finding some, but cant find anything related.
All my flags are default as given at install.

it must be some element in the dashboard that causes the crash, yet i dont know how to troubleshoot it.
And it must be a Thorium related issue, as its the only browser having issues.

any idea's?

In the console i get the following 
The time outs are the ones that recover, if i just wait those 4 seconds, everything gets going again, this happens when loading a dashboard.
The last error the 'requestIdleCallback' is when the page fully becomes unresponsive, and doesnt recover anymore.
On each of these errors my cpu goes crazy, on the timeouts its only for 4 seconds, on the requestIdleCallback its aslong as i am on that page. if i go to another tab, while its still open my cpu calms down again, but as i am accually looking at that page that is unresponsive then my cpu goes crazy.

![image](https://github.com/Alex313031/Thorium-Win/assets/104201837/ecfae3d0-a414-48f8-b43a-42d9f9055d97)

Hope this might help.

**Comment by gz83** [comment]
Please try to troubleshoot the issue by running your Home Assistant in incognito mode and without passing any experimental flags.

**Comment by Werewolfke** [comment]
> Please try to troubleshoot the issue by running your Home Assistant in incognito mode and without passing any experimental flags.

The exact same happens in Incognito mode, all flags in the chrome//:flags page are default / in the reset possition. the few experimental in the top bar on the right, dont change anything either, either in default or dissabled the behaviour stays the same.

**Comment by gz83** [comment]
Did you develop the code for this Home Assistant page yourself?

**Comment by Werewolfke** [comment]
> Did you develop the code for this Home Assistant page yourself?

i made the dashboards myself with a few custom components nothing out of the ordinary, its all yaml code, nothing that the browser needs to process. all calculations and work is done on homeassistant itself.
As soon as i try to edit it, it completly locks, so via thorium i cant see what the issue might be. other browsers dont give any errors that might explain it.

**Comment by Werewolfke** [comment]
update; editting does work, i just need to wait more the a minute before it respons. its like every page change or every other view i click it needs time to process every single thing it needs. it takes more then 4 seconds every click before it loads something, or just times out completely.

After the edittor finely did load, no error showed up. so i can not say what happens.

**Comment by Werewolfke** [comment]
Another update; this happens on other home assistant instances too. I have a similar setup at work, and it crashes too. Again, only on Thorium.

**Comment by gz83** [comment]
Please try to rename thorium.exe to chrome.exe and check if the problem you are experiencing can be reproduced again.

**Comment by Werewolfke** [comment]
This does not help, weirdly enough 👀 nothing changes. It still crashes.

**Comment by gz83** [comment]
Would you mind telling me what home assistant system you're using?

**Comment by Werewolfke** [comment]
i do not know what u mean by system, but home assistant itself runs on hoas itself, and at work its the core version installed with python., so both run on linux, one on hoas, i do not know if its debian or something. the ona at work is debian. two totally different systems. 
Thorium, the browser is all on windows 11 installed the same way as posted in the original  post with the avx2 mini installer.
This is tested on a laptop, a pc, and another work laptop, and its clear that the stronger the cpu the faster the bump/hang passes or the slower the cpu, the longer the hang occurs, or faster the full pages blocks.
Again this does not seem to happen on the mobile thorium browser. should i try a different installer? all my pc's have a intel gen 11 or newer.

**Comment by gz83** [comment]
Thanks for providing me with this information, in the meantime, is this home assistant open source? I'd love to learn more and try to help you troubleshoot the issue.

**Comment by Werewolfke** [comment]
Home assistant itself is open source, and easy to set up. i will try otherwise to create a temporary instance for you to visit to see if it occurs to0 on your end. I'll send a update here with the link by tomorrow if it works.

**Comment by Werewolfke** [comment]
lab.werewolfkeyoung.com should work for now (i trust everyone here to not abuse the instance tho i did secure it.)
user is 
name; test
password; test123

This is a stripped version of what my home setup looks like, so there will be alot of entities that dont show as available.
but even here i get the same issue. 
I see its a bit better on this stripped version yet u can still see on the left jumping between the server panel and to the overview tab, a few times it hangs... this should be instant, not a single ms of a stutter on other browsers. the performance is bad to say it simple. so far this is the only sort of site that has this issue.

**Comment by Werewolfke** [comment]
Since there appears to be no progress on this matter im going to close this issue, and move on my search for a working browser.
The Website is now closed again.

**Comment by gz83** [comment]
I'm sorry, I've been busy with development on non-Windows platforms in the past few days. If it's convenient, could you provide temporary access again?
