### ISSUE TITLE
[crash issue] "Live Caption: thorium.exe - System Error"

### ISSUE THREAD

**Issue by enihcam** [Alex313031/Thorium-Win#232]
**System Details**
![image](https://github.com/Alex313031/Thorium-Win/assets/7010097/d167d38a-1d47-4f08-85b1-9e159482e12d)
![image](https://github.com/Alex313031/Thorium-Win/assets/7010097/60727189-3ca9-40a9-a637-029fdb546010)

**Problem**
> "Live Caption: thorium.exe - System Error" came from nowhere and browser crashed.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/7010097/e10a5e9a-98de-420e-8a8b-d17a54659b6b)

**Additional Notes**

**Comment by gz83** [comment]
Please do not use this feature, non-Chrome versions will not be fully supported.

**Comment by enihcam** [comment]
disabled.

**Comment by enihcam** [comment]
> Please do not use this feature, non-Chrome versions will not be fully supported.

where do i find a list of unsupported/partially-supported features? i'll disable all of them.

**Comment by gz83** [comment]
Sorry I can't accurately count all the unavailable or partially supported features.
