### ISSUE TITLE
Emoji Flags show as black flag instead of the intended flag

### ISSUE THREAD

**Issue by Owen-3456** [Alex313031/Thorium-Win#237]
**System Details**
 - OS: Windows 10 Version 22H2 (OS Build 19045.4529)
 - Thorium Version 124.0.6367.218 (Official Build) (64-bit)

**Problem**
Emoji Flags show as black flag instead of the intended flag

**Screenshots**
Thorium:
![thorium_p10xfA1Nke](https://github.com/Alex313031/Thorium-Win/assets/78411938/af70d382-b8bd-4ce2-9e13-f8beb13e6395)
Firefox and Chrome:
![firefox_yu3AmZ2vGf](https://github.com/Alex313031/Thorium-Win/assets/78411938/bd6e164d-ab73-474c-9e3e-a176db115615)

**Comment by gz83** [comment]
Have you disabled all extensions or tried in incognito mode? Also, please provide the URL of the webpage where this problem occurs.
