### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by piettrangelo** [Alex313031/Thorium-Win#238]
I really like Thorium, I use it for everyday tasks and often for work.

But its updates now still depend on one person and we haven't seen an update arrive in almost 2 months.

Is there any possibility of adding some sort of item on the site where we could track the progress of the next build/next missing founder? So that at least there would be a way to understand where development is at.

Much respect for the work and the founder,
Alex

**Comment by Koatohee** [comment]
yeah.

**Comment by AJolly** [comment]
I only started recently using this, and I can't go back. It's soo much faster than chrome. I'd have to figure out how to go compile it myself from scratch if it stopped being updated.
