### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by Galamooth** [Alex313031/Thorium-Win#244]
Some time ago I noticed that several people, including me, have made requests and there is no response, and it is also not updated. Can someone please tell me if the project is abandoned?  There are already several incompatibilities with the use of the Internet, Thorium must be updated, otherwise it will be necessary to change browsers unfortunately.   Mr. Alex, can you comment on this? Users need a response, thank you very much

**Comment by gz83** [comment]
I have answered in other similar questions that this project has not been abandoned.

**Comment by kLiHz** [comment]
This repo is more like a place for publishing Windows releases, so I think it's normal for it to be quiet until there's a new version. However you can check [commits in the thorium repo](https://github.com/Alex313031/thorium/commits/main/) and you would see Alex has been contributing to it from time to time.
