### ISSUE TITLE
Lagging a lot while using google web apps

### ISSUE THREAD

**Issue by pousoupou** [Alex313031/Thorium-Win#245]
**System Details**
 - OS: Windows 10
 - Thorium Version M124.0.6367.218

**Problem**
When opening and using a google web app (such as: gmail, maps, drive, etc), thorium almost goes unresponsive until all emails or the whole area on maps load. On chrome with the same setup (google account, extensions, etc) everything run smoothly.

**Comment by weskerty** [comment]
add --no-sandbox ?

**Comment by pousoupou** [comment]
other than the warning about the unsupported flag, nothing else changed. it still lags a lot when visiting google apps

**Comment by gz83** [comment]
I cannot reproduce the problem you encountered locally, and version 126 will be released soon. Please test again after version 126 is released.

**Comment by weskerty** [comment]
> other than the warning about the unsupported flag, nothing else changed. it still lags a lot when visiting google apps

Use Nvidia with Custom settings?
That causes all chromium browsers to lag when playing video.

**Comment by pousoupou** [comment]
it seems that whatever the issue was, is now fixed with the new version.
