### ISSUE TITLE
`#close-confirmation` doesn't work anymore on v126

### ISSUE THREAD

**Issue by Unknown78** [Alex313031/Thorium-Win#249]
## Backgrounds
 - OS: Windows 11
 - Thorium Version: [Thorium_SSE3_126.0.6478.231.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M126.0.6478.231)
## Problems

Descriptions of the flag:

> Close Confirmation
> Show a warning prompt when closing browser window(s). – Mac, Windows, Linux, ChromeOS, Fuchsia, Lacros
> 
> `#close-confirmation`

Settings of it:

> - Default
> - Show confirmation with last window
> - Show confirmation with multiple windows

Unlike the previous version that it's still working with a bug in `multiple windows` option: https://github.com/Alex313031/Thorium-Win/issues/240

With the new Thorium v126, either the `last window` or `multiple windows` option doesn't work anymore.

**Comment by chaoscreater** [comment]
Can confirm the issue on my end too.

**Comment by Unknown78** [comment]
@chaoscreater It's fixed in v128
Thank you Alex
