### ISSUE TITLE
can't open www.hoyolab.com

### ISSUE THREAD

**Issue by CCCAUCHY** [Alex313031/Thorium-Win#259]
**System Details**
 - OS: windows 10
 - [Thorium Version 126.0.6478.231](https://github.com/Alex313031/Thorium-Win/releases/download/M126.0.6478.231/thorium_AVX2_mini_installer.exe)

**Problem**
can't open www.hoyolab.com

**Screenshots**
![image](https://github.com/user-attachments/assets/2b9fe9da-ab45-4a43-bb67-b1cd9eaf724f)

**Additional Notes**
Edge 128.0.2739.54 can open it

**Comment by 0hip** [comment]
![image](https://github.com/user-attachments/assets/f2101d93-6cda-4d98-903c-3b4554fef555)
![image](https://github.com/user-attachments/assets/3a955793-4fd6-4ded-8ca9-17d4bf0bbb08)

**Comment by CCCAUCHY** [comment]
I can open it now...why
