### ISSUE TITLE
Can't switch different tabs when clicking top 1px width edge of screen with Th24 enabled

### ISSUE THREAD

**Issue by LeslieYon** [Alex313031/Thorium-Win#260]
**System Details**
 - OS: Windows 10
 - Thorium Version: [126.0.6478.251](https://github.com/Alex313031/Thorium-Win/releases/tag/M126.0.6478.251)

**Problem**
Can't switch different tabs when clicking top 1px width edge of screen with Th24 enabled, this happens when thorium are fullscreen.

**Comment by Linnniop** [comment]
Yes, me too

**Comment by CCCAUCHY** [comment]
I call that Edge-Control ,it is an importance feature, make windows easier to use than MacOS

**Comment by 404neko** [comment]
Same
