### ISSUE TITLE
White line under bookmarks bar with Th24 enabled and Web Store themes applied

### ISSUE THREAD

**Issue by Amanoki** [Alex313031/Thorium-Win#263]
**System Details**
 - OS: Windows 10
 - Thorium Version: M126.0.6478.251

**Problem**
Steps to reproduce:
1. Fresh install, enable `chrome://flags/#thorium-2024`, enable `Show bookmarks bar`.
2. Install a theme from Chrome Web Store, such as [this one](https://chromewebstore.google.com/detail/annfbnbieaamhaimclajlajpijgkdblo).
3. A white line shows up under the bookmark bar.

Note: Not all themes have the issue, but the ones that do are quite a lot, it should be easy to see it by installing random themes.
The white line does not exist when `Enable Experimental Thorium 2024 (Th24) UI` is disabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/c3fa49b6-cd75-4d3d-80ff-51ce955ca3ff)
![image](https://github.com/user-attachments/assets/f17dc540-2c6f-41ba-9d8a-87f672926505)

**Comment by Alex313031** [comment]
@Amanoki OK thanks. I'll look into it for the M127 release.

**Comment by Alex313031** [comment]
@Amanoki Can you enable the `chrome://flags/#force-disable-tab-outlines` flag, and see if it fixes it?

**Comment by Amanoki** [comment]
> @Amanoki Can you enable the `chrome://flags/#force-disable-tab-outlines` flag, and see if it fixes it?

Enabled it (no tab outlines) on BETA 2, the bookmarks bar white line is still there.

P.S. Tried out BETA 2 and I love the context menu btw, other features look good, thanks for the fixes!

**Comment by Amanoki** [comment]
Fixed in M128.0.6613.189. Very much appreciate your hard work on Th24!

**Comment by Dxmns** [comment]
May i ask how you fixed this issue, im using different chromium browsers, a solution would be very much appreciated
