### ISSUE TITLE
M126.0.6478.251 - Can not print (Print preview failed)

### ISSUE THREAD

**Issue by PeterCodar** [Alex313031/Thorium-Win#266]
**System Details**
 - OS: Windows 10 Pro 22H2, build 19045.4780
 - Thorium Version BETA "Th24" build - M126.0.6478.251

**Problem**
I can not print a webpage loaded in Thorium BETA "Th24". After pressing CTRL + P or right-click context and Print I don't see any preview, only a grey screen with the hint "Print preview failed" (Druckvorschau fehlgeschlagen). 
All options (like the printer selection) are grayed out too.

**Screenshots**
![image](https://github.com/user-attachments/assets/d2c6500a-339e-4ea0-ad54-d5591eb48f89)

**Additional Notes**
none

**Comment by gz83** [comment]
The new version further uses LPAC. Please use the mini installer to install the browser to ensure that everything works properly.

If you really can't install the browser via the mini installer, make sure to pass the --disable-features=PrintCompositorLPAC parameter.

**Comment by PeterCodar** [comment]
Thank you very much for the super-fast and working answer!

I'm using the "portable" version of the [BETA Th24](https://github.com/Alex313031/Thorium-Win/releases/download/M126.0.6478.251/thorium_Th24_126.0.6478.251.zip). 
With your additional command line parameter
`--disable-features=PrintCompositorLPAC`
I can print web pages as usual (including the creation of PDF).

**Comment by Unknown78** [comment]
@gz8
I've also observed it in [Thorium_SSE3_128.0.6613.189.zip](https://github.com/Alex313031/Thorium-Win/releases/tag/M128.0.6613.189)

What does LPAC stands for?
Why it prevents print preview?
What is the disadvantage of disabling it?

**Comment by gz83** [comment]
This is related to the sandbox, please see Google's official documentation.

https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox.md#Less-Privileged-App-Container-LPAC

Google recently changed the print preview code and introduced LPAC for it. If the browser is not installed in the normal way, some sandbox functions will not be successfully registered with the system, resulting in print preview errors.


Turning off this feature may make your browser less secure.

@Unknown78

**Comment by Theletha** [comment]
> This is related to the sandbox, please see Google's official documentation.
> 
> https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox.md#Less-Privileged-App-Container-LPAC
> 
> Google recently changed the print preview code and introduced LPAC for it. If the browser is not installed in the normal way, some sandbox functions will not be successfully registered with the system, resulting in print preview errors.
> 
> Turning off this feature may make your browser less secure.
> 
> @Unknown78

i installed thorium with this installer but it still giving the same print error as in the post here, did i install it incorrectly? 
![image](https://github.com/user-attachments/assets/7a3fb7fe-8c90-4340-92b2-226033a97638)

**Comment by gz83** [comment]
Can you provide the relevant web address?
@Theletha

**Comment by Theletha** [comment]
> Can you provide the relevant web address? @Theletha

https://github.com/Alex313031/Thorium-Win/releases/download/M128.0.6613.189/thorium_AVX2_mini_installer.exe

**Comment by gz83** [comment]
I mean the web link of the PDF file where the problem occurs

@Theletha

**Comment by Theletha** [comment]
> I mean the web link of the PDF file where the problem occurs
> 
> @Theletha

oh it happened on everything as soon as you did CTRL+P on whatever it would give Print preview failed and i wouldn't be able to select anything on the right hand side.

**Comment by gz83** [comment]
Try passing the --disable-features=PrintCompositorLPAC parameter

Also, have you used .zip version before?

@Theletha

**Comment by Theletha** [comment]
Yes im already using that parameter, it is working with that for now.

no i have not used the zip version yet

**Comment by 3357212328** [comment]
> Thank you very much for the super-fast and working answer!
> 
> I'm using the "portable" version of the [BETA Th24](https://github.com/Alex313031/Thorium-Win/releases/download/M126.0.6478.251/thorium_Th24_126.0.6478.251.zip)。 With your additional command line parameter `--disable-features=PrintCompositorLPAC` I can print web pages as usual (including the creation of PDF).

Could you tell me how to use this "--disable-features=PrintCompositorLPAC" parameter?

**Comment by 0hip** [comment]
> > Thank you very much for the super-fast and working answer!
> > I'm using the "portable" version of the [BETA Th24](https://github.com/Alex313031/Thorium-Win/releases/download/M126.0.6478.251/thorium_Th24_126.0.6478.251.zip)。 With your additional command line parameter `--disable-features=PrintCompositorLPAC` I can print web pages as usual (including the creation of PDF).
> 
> Could you tell me how to use this "--disable-features=PrintCompositorLPAC" parameter?

 "portable" version:

![Image](https://github.com/user-attachments/assets/6229ef1b-35d5-4f90-b66a-b21d121f937f)
