### ISSUE TITLE
Would like code that resets the settings when moving portable install to be removed

### ISSUE THREAD

**Issue by K4sum1** [Alex313031/Thorium-Win#27]
I use the portable Thorium, and if I move to another machine it resets a bunch of settings and is a pain to set back up. This has basically prevented me from using Chromium anything for any remotely serious task.
![ScreenShot_20230204095044](https://user-images.githubusercontent.com/77039240/216776980-27de6588-ee76-4070-92e8-9506e446716f.png)

**Comment by K4sum1** [comment]
![ScreenShot_20230329142301](https://user-images.githubusercontent.com/77039240/228646008-0abf9a02-8268-4597-b1f0-28d9344e662f.png)

**Comment by gz83** [comment]
> ![ScreenShot_20230329142301](https://user-images.githubusercontent.com/77039240/228646008-0abf9a02-8268-4597-b1f0-28d9344e662f.png)

@K4sum1 

Please update your browser to our latest released version first

**Comment by K4sum1** [comment]
110 works on 7?

**Comment by gz83** [comment]
> 111 works on 7?

@K4sum1 

You did not previously indicate which system you are currently using.

Unfortunately, version 109 does not include these two flags, so you may not be able to use them
