### ISSUE TITLE
rounded coner

### ISSUE THREAD

**Issue by offferu** [Alex313031/Thorium-Win#271]
![cr23](https://github.com/user-attachments/assets/07edb3a6-27a3-4335-8f3d-795df8ebd2f9)

![th24](https://github.com/user-attachments/assets/1f5a405e-b652-4265-9de3-40706f35a58b)

Above one is cr23, it has rounded coner "2",  could reserve it in th24?

**Comment by Alex313031** [comment]
@offferu What is the problem

**Comment by offferu** [comment]
> @offferu What is the problem

closed. people have diffent flavor
