### ISSUE TITLE
For the love of god, I've accidentally exited out of my regular & incognito browser session multiple times. can you please

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/Thorium-Win#28]
For the love of god, I've accidentally exited out of my regular & incognito browser session multiple times, because my mouse cursor(i have a touchpad) accidentally shot towards the exit button & touchpads are very sensitive so my fingertip also registered as a left click. Or I accidentally hit the exit button instead of the "restore down" or "minimize" button right next to it. Can you please make an
"are you sure?" popup to make sure i actually want to exit out of my browser session?
Brave browser, Chrome browser,etc have this failsafe. 
-Thanks Frickmeister!

**Comment by Alex313031** [comment]
@gz83 @Intellectual234  We can probably add this to thorium as a chrome://flags flag.

**Comment by Alex313031** [comment]
@Intellectual234 We are working on adding this feature. I would also recommend Session Buddy (which is what I use) > https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko

**Comment by Intellectual234** [comment]
@Alex313031 ,Thanks ,yeah i use session buddy already, been using it for 9 years now. But that doesnt solve a lot of the problem of my OP. And session buddy doesnt normally work on incognito, u gotta finagle it to.

**Comment by Alex313031** [comment]
@Intellectual234 We added these flags to the latest release as well as the linux and AVX2 releases.

**Comment by Alex313031** [comment]
@Intellectual234 @gz83 Fixed. CLosing as completed.
