### ISSUE TITLE
Browser crashCrash on bookmark button pressed (Bookmark this tab make browser crash)

### ISSUE THREAD

**Issue by BruteForcePro** [Alex313031/Thorium-Win#280]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g. Thorium_AVX2_126.0.6478.231]

**Problem**
When we press little flag of bookmark this tab, the Thorium crash, this happen with old versions, too, i try to disable this flag around, but cannot find the settings. P.S. I Don't know if this issue happen with other builds AVX2 and SE3 Surely

Give us a way to disable this flag, if we can.
Keep doing the beautiful things, this browser is awesome, cheap and fully powerfully stable, Thank You <3

**Screenshots**
![Screenshot-30_09_2024-07_12_12487](https://github.com/user-attachments/assets/746cdcf4-2e3f-490e-983b-bef9393bccb8)

**Comment by gz83** [comment]
Please provide the version and flags you are currently using

**Comment by BruteForcePro** [comment]
Version: 126.0.6478.231
Flags;
--user-data-dir="%BatchDir%USER_DATA" ^
--allow-outdated-plugins ^
--disable-logging ^
--disable-breakpad ^
--disable-encryption ^
--disable-machine-id ^
--disable-default-apps ^
--disable-hang-monitor ^
--disable-popup-blocking ^
--disable-prompt-on-repost ^
--disable-sync ^
--disable-translate ^
--disable-ipc-flooding-protection ^
--metrics-recording-only ^
--mute-audio ^
--no-first-run ^
--no-default-browser-check ^
--process-per-site ^
--autoplay-policy=no-user-gesture-required ^

**Comment by gz83** [comment]
Please try to bookmark the page without passing flags to check if it is the flags that are causing the crash. Also, some flags are enabled by default in Thorium or can be managed via chrome://flags.

**Comment by BruteForcePro** [comment]
Helll thank you, i check, and this flag create the problem: --disable-sync if you need it for fix
