### ISSUE TITLE
thorium doesnt open

### ISSUE THREAD

**Issue by nex577** [Alex313031/Thorium-Win#282]
**System Details**
 - Windows 10 64x
 -Th24 beta 2 - M126.0.6478.251

so i downloaded the latest version (mini installer) and when it finish to install it the browser doesnt open , it crashes , i already looked on the task manager and there is the process of thorium but instantly crashes , i have an intel core i3 2nd gen btw idk if thats the problem , i have tried other versions and they doesnt work neither (M126.0.6478.251 and M126.0.6478.231)

**Comment by gz83** [comment]
Please try the SSE3 version of .231

**Comment by nex577** [comment]
thanks that worked , i always been confused about all those versions like avx sse4 , that stuff

**Comment by gz83** [comment]
Please try to use software such as CPU-Z to view the instruction sets supported by the processor. If the processor is too old, according to experience, the SSE3 version is generally preferred, which is also what Google is currently using.
