### ISSUE TITLE
How to change this to be the same as M126

### ISSUE THREAD

**Issue by CCCAUCHY** [Alex313031/Thorium-Win#288]
How to change this to be the same as M126
![image](https://github.com/user-attachments/assets/9988469c-c2d0-4132-bde9-3a1ee9ce0430)
change this ↑ to this ↓
![image](https://github.com/user-attachments/assets/72adda52-e994-4c67-83d9-4c66feff791f)
I don't like the **Line Drawing** or **Edge Outlining**

**Comment by gz83** [comment]
You can turn off the relevant features in the chrome flags page

**Comment by bonbonsiregar** [comment]
> You can turn off the relevant features in the chrome flags page

which flags?

**Comment by gz83** [comment]
> > You can turn off the relevant features in the chrome flags page
> 
> which flags?

Tab outline, this is mainly for low contrast.

**Comment by SyberGen333** [comment]
Enable the "Disable Tab Outlines" and it should go back to the M126 style

![image](https://github.com/user-attachments/assets/7265644e-5dd9-48a9-9050-62b65ba291df)
