### ISSUE TITLE
Chrome Refresh 2023 back pls

### ISSUE THREAD

**Issue by techadvyt** [Alex313031/Thorium-Win#290]
**Is your feature request related to a problem? Please describe.**
I don't like the Th24 UI, it's just too old for me, I like the new and vibrant Chrome Refresh 2023 but I cannot find any option to enable it.

**Describe the solution you'd like, including relevant patches or source**
Add an option to enable Chrome Refresh 2023.

**Comment by gz83** [comment]
You can turn off the Thorium 2024 UI in the chrome flags page

**Comment by techadvyt** [comment]
It still doesn't work
![image](https://github.com/user-attachments/assets/515ba3bb-58ab-43c9-bb3c-276570c9b8c7)

**Comment by gz83** [comment]
Please tell me which parts you want to change back to refresh 2023 style, and I will give you guidance

**Comment by techadvyt** [comment]
I want to change almost all of them.

**Comment by gz83** [comment]
Sorry, we will not provide a way to completely restore the interface to the refresh 2023 style for the time being. Even if you manage to turn off some flags, Thorium will still have some elements that are different from the refresh 2023 style.

In addition, it is still recommended that you indicate the places where you want to revert to the refresh 2023 style, and I will provide you with relevant guidance.

**Comment by techadvyt** [comment]
I see.
