### ISSUE TITLE
Will Thorium ever get vertical tabs? 

### ISSUE THREAD

**Issue by xweiba** [Alex313031/Thorium-Win#292]
I want to move back from Edge but I have gotten to used to vertical tabs and don't want to give them up (extensions won't cut it unless they can reduce the browser's vertical frame like Edge does). It's an amazing feature, I don't understand how Google hasn't ported it yet :-/ 

Can Thorium do that?

**Comment by gz83** [comment]
Vertical tabs don't seem to have received much attention from Google at this stage, and the feature breaks the horizontal tabs logic that has existed for many years.

I personally have some interest in vertical tabs but it's not a strong one. In addition, I or Alex may help Thorium implement vertical tabs in the future.

**Comment by xweiba** [comment]
> Vertical tabs don't seem to have received much attention from Google at this stage, and the feature breaks the horizontal tabs logic that has existed for many years.
> 
> I personally have some interest in vertical tabs but it's not a strong one. In addition, I or Alex may help Thorium implement vertical tabs in the future.

Thanks y'all for your efforts~

**Comment by yeezylife** [comment]
vertical tabs and Hide title bar.  perfection
