### ISSUE TITLE
Google voice call & web browser spotify malfunction,

### ISSUE THREAD

**Issue by Username23453** [Alex313031/Thorium-Win#30]
1.) When i try to make a call with google voice, it calls out, but i cant hear it dialing or anyone answer, but in brave browser it works fine. voice.google.com. It appears that google voice is calling out with thorium & working, but that i just cant hear anything whatsoever. I also want to explain the ramifications of this, when I tried to use it with Thorium. It would call out, & have no sound at all, but when I'd call my own phone, my phone rang, even though i couldnt hear anything on google voice's side. I didnt think there would be an issue with Thorium, so i didnt think about that & assumed the problem was being caused by something else, So I thought the 1st phone # i had called had blocked me. And also if this happens with other people, they may think this too & experience distress, or they may think it's google voice thats the problem, & that will cause them distress, etc, or they may think they have a virus. So its important to fix this issue soon, or maybe just warn thorium users about this. Nevertheless, I'm enjoying the thorium experience & appreciate it.

2.) https://open.spotify.com/  web browser version malfunctions & skips randomly, wont play a song properly, very glitchy.  This also can cause other issues with the user, they may think they have a virus or that spotify is the one malfunctioning & not thorium & cause them to go on a wild goose chase, so a warning would be a good idea with this too.

**Comment by Intellectual234** [comment]
I have no idea, but this is all my browser tells me "Version 109.0.5362.0 (Official Build) (64-bit)"

**Comment by Intellectual234** [comment]
@gz83, thanks! before i install avx2 or sse3, is it going to delete or reset any of my browser configurations or data?

**Comment by Intellectual234** [comment]
@gz83 , are there any OS's or laptops that AVX2 & SSE3 version would have issues running in? before i try them.

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , I have tested the avx & avx2 versions of thorium on windows 7 & spotify & google voice malfunctions with both of them. I have not had the chance to test if sse3 version works or not. But i know something new though, which is that the thorium for linux "thorium-browser_110.0.5481.178_amd64.deb", the newest version for thorium, Link: https://github.com/Alex313031/thorium/releases/tag/M110.0.5481.178, 

Spotify & google voice work flawlessly on this version & i can even ad block on spotify web browser version. This issue still should remain open though until the sse3 version is tested & the problem is solved.
-Thank you.

**Comment by Intellectual234** [comment]
@gz83 , a few weeks ago it didnt work, i dont know about now though. I am overwhelmed with things right now, someone should test it out.

**Comment by Intellectual234** [comment]
I dont think this is solved with Thorium window, @Alex313031?

**Comment by gz83** [comment]
> I dont think this is solved with Windows Thorium, @Alex313031?

@Intellectual234 

Does the 111 version of chromium have the problem you are experiencing?

**Comment by Intellectual234** [comment]
@gz83 , i think i checked & it still had the problem but i cant remember, I only have ZorinOS right now, so I am not able to test it, but when I was using Thorium for windows, this issue was a real problem, & inconveniencing.

**Comment by gz83** [comment]
> @gz83 , i think i checked & it still had the problem but i cant remember, I only have ZorinOS right now, so I am not able to test it, but when I was using Thorium for windows, this issue was a real problem, & inconveniencing.

@Intellectual234 

In this case, let's temporarily set this issue to closed status. If you have the opportunity to use thorium on windows and encounter the same problem in the future, you can reopen this issue and report the problem to us.

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , I've already reported the problem to both of you & documented it plenty. Perhaps one of you could run a windows 7 in VM & test it,because it never worked for me. I am not in a position to do so right now.

**Comment by Aedon** [comment]
@gz83 112 has the spotify web player problem described by @Intellectual234 . If it's a playlist it keeps skipping songs, till it reaches the end and autoplays other songs. If it's a single song then it will always plays the first 10 seconds and rest will be silent.

**Comment by Intellectual234** [comment]
@Aedon , thanks yeah they need to fix this issue. The Thorium version I'm using for ZorinOS though works fine. Who's 112?

**Comment by Aedon** [comment]
>Who's 112?

By 112 I am referring to the version.

**Comment by Aedon** [comment]
@Intellectual234 It's a grim world we live in; not thorium's fault.
https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-873456050

**Comment by Intellectual234** [comment]
@Aedon , thank you, very helpful.

**Comment by gz83** [comment]
Do Google Voice and Spotify still have problems? If it still exists, please open the following two pages when the problem occurs, and upload all the content under these two pages to here, so as to locate the problem

chrome://media-internals/#cdms

chrome://histograms/#Media.EME

@Aedon @Intellectual234

**Comment by Aedon** [comment]
@gz83 
[histograms.txt](https://github.com/Alex313031/Thorium-Win/files/11643370/histograms.txt)
![Screenshot 2023-06-03 233427](https://github.com/Alex313031/Thorium-Win/assets/72438130/3c756a09-3a25-407f-aaf8-34ae176be985)

**Comment by gz83** [comment]
There is a suspected exception with the widevine component, I will discuss this with Alex

**Comment by gz83** [comment]
![image](https://github.com/Alex313031/Thorium-Win/assets/17492865/f69bc4e4-5ce1-4bd4-9ff8-cb13d11118e6)

Please open the chrome://flags page and open the three experimental flags shown in the image to see if it solves the problem you are experiencing.

@Aedon @Intellectual234

**Comment by Aedon** [comment]
@gz83 The songs now play for 0.5s or so on open.spotify.com before skipping like before.

**Comment by Alex313031** [comment]
@Aedon @Intellectual234  Can you try the latest M114 release. We enabled a new widevine path.

**Comment by Aedon** [comment]
Tried, the issue is still there.

**Comment by MisterLotospol** [comment]
> Tried, the issue is still there.

Has this been fixed ?

**Comment by MisterLotospol** [comment]
> @MisterLotospol , i dont know about google voice, but spotify works great. i have a new/different version though for linux.

A shucks I use windows and tried but still no go for me ...
