### ISSUE TITLE
browse keeper rogue

### ISSUE THREAD

**Issue by BabyBoySnow** [Alex313031/Thorium-Win#301]
When I first installed thorium, I was surprised to see some extensions already enabled by default. Not knowing what one of these was (browse keep) I did a quick search for it, and found that it's been declared as a rogue plugin. 
https://www.pcrisk.com/removal-guides/27346-browse-keeper-adware 
Also it's not longer available in the chrome webstore. I strongly recommened removing it from the build. Thanks for reading!

**Comment by gz83** [comment]
Thorium will not embed malicious extensions into the browser. Can you upload a screenshot of the chrome://extensions page?

**Comment by BabyBoySnow** [comment]
> Thorium will not embed malicious extensions into the browser. Can you upload a screenshot of the chrome://extensions page?

It seems that how I previously downloaded it came with this extension, and has since been removed. I'm unsure of why it loaded in by default as I don't believe I've ever had it associated with my google accounts before, downloaded a fresh installer from releases though, and signed in as guest and it's just ublock and docs offline. Odd to say the least. Sorry for my mistake!
