### ISSUE TITLE
I blocked an extension notification. I don’t know how to recover

### ISSUE THREAD

**Issue by A81N9** [Alex313031/Thorium-Win#306]
I blocked an extension notification. I don’t know how to recover

![image](https://github.com/user-attachments/assets/71e53207-910c-44be-9e09-d30a18bde83a)

I did not find the corresponding configuration item in `chrome://settings/content/notifications`

![image](https://github.com/user-attachments/assets/b00b3336-c34b-453d-b5af-30939fbb59c5)

**Comment by gz83** [comment]
Please try https://moeking.me/2022/09/26/659/

**Comment by A81N9** [comment]
> Please try https://moeking.me/2022/09/26/659/

Thank you for your reply.
This method perfectly solves my problem.
