### ISSUE TITLE
"Find Tool" box annoyingly moving around while using it, while clicking it's up/down buttons

### ISSUE THREAD

**Issue by Intellectual234** [Alex313031/Thorium-Win#31]
I've had this problem forever, i think this problem even occurs with Brave browser & Chrome browser, not sure though.
So when i use the "Find Tool" to find a word on a website, the "find tool" itself, half way through the words i'm combing through, the box will move instantaneously an inch to the right or left **while** I'm still clicking on it rapidly, which causes me to accidentally click the bookmark **underneath** that tool's window, or where that tool window just was, but moved away from, so i then accidentally rapidly click on the bookmark, i then lose the webpage I'm on & lose the place/position on the page & progress I made with combing through it, searching for a word. This is incredibly annoying & inconveniencing. Also its baffling, who **in the world** would design it to do this? for the box to jerk around like this? I know it wasnt the designers of thorium of course, probably google chrome.  This problem also doesnt just occur with websites, but with pdfs, etc that you have opened up on the browser.

Please see this video screen recording i made below.
SOLUTIONS, that i can think of. 1.) Stop it from jerking around, make it stay in one place.
Solution 2.) or find a way, instead of using the mouse cursor to click the find up or find down button, have keyboard shortcuts that one can press rapidly instead. Like Alt+S for UP, & Alt+ D for DOWN.

https://user-images.githubusercontent.com/105397593/219855450-ce992482-6ab5-4d30-bbc1-46bf630ec8fb.mp4

**Comment by Alex313031** [comment]
@gz83 @Intellectual234 Im not sure how to fix this. Seems like an upstream issue.

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , could you guys try to please fix this, and/or please report it to chromium for me?

**Comment by gz83** [comment]
> @gz83 , @Alex313031 , could you guys try to please fix this, and/or please report it to chromium for me?

@Intellectual234 

I think this should be fixed by chromium, but please note that the problem you are experiencing is not necessarily a bug

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 , i think it has to be a bug, i cannot think of any sane reason why the find tool window would jerk around unpredictably like that.

**Comment by gz83** [comment]
> @gz83 , @Alex313031 , i think it has to be a bug, i cannot think of any sane reason why the find tool window would jerk around unpredictably like that.

@Intellectual234 

Whether this is a bug is up to the chromium developers, if they don't think it's a bug, chances are it's a feature they want to implement.

Please also note that this issue has been closed, and it is not recommended to post new information here.

**Comment by Intellectual234** [comment]
@gz83 , @Alex313031 ,, could you guys try to please report it to chromium for me?
