### ISSUE TITLE
Remove search keyword history in address bar

### ISSUE THREAD

**Issue by Itoktsnhc** [Alex313031/Thorium-Win#317]
I hope to be able to remove the switch that gives the search keyword history in the address bar. It turns out that this switch is controlled by this flag: **omnibox-zero-suggestions-on-ntp**
![image](https://github.com/user-attachments/assets/a7bbb58b-0c45-435c-ada7-1b52a3588544)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like, including relevant patches or source**
I use this extension  https://chromewebstore.google.com/detail/hcos-hide-chrome-omnibox/aldijnffnfojelcpcfoekkeifffkhldo?pli=1 to delete all google search related histories

**Additional Notes**
No

**Comment by gz83** [comment]
I can't find the flag you mentioned in Thorium. Also, since you can delete the history using an extension, there is no other problem here.
