### ISSUE TITLE
I got the latest mini installer downloaded,"25th Release - M109.0.5414.120", Alex313031 told me

### ISSUE THREAD

**Issue by Username23453** [Alex313031/Thorium-Win#32]
to download the installer to c:\windows\temp. He told me this many months ago, does it matter?
Should i only install it to that folder? 
-Thanks

**Comment by Intellectual234** [comment]
I dont understand what u mean or r asking. I just downloaded it today, what date do u want to see?

**Comment by Intellectual234** [comment]
![image](https://user-images.githubusercontent.com/105397593/219868690-7115d346-af6d-407d-96c0-ac386c357393.png)

**Comment by Intellectual234** [comment]
I dont understand why u are asking me these questions? with all respect. I downloaded the installer today. Please explain.

**Comment by Intellectual234** [comment]
Yes, I am using IDM, please explain how IDM can cause problems, and what problems do u mean?

**Comment by Intellectual234** [comment]
**"do other files also have this problem?"**
--Have what problem?

Also, please explain why it matters what my thorium installers creation file date says?

**Comment by Intellectual234** [comment]
**"the time of the file."**
--Yes, and how is that a problem? it has installed fine today. I was just wondering why Alex313031 told me to install the mini installer in the c:\windows\temp folder?  thanks for all your help tho, regardess. :)

**Comment by Intellectual234** [comment]
Alex told me in december of 2022. See screenshot below.

![image](https://user-images.githubusercontent.com/105397593/219945910-84d3581c-2783-416f-992e-0e75b9c7ea8d.png)

**Comment by Alex313031** [comment]
@Intellectual234 I was saying that the chrome auto updater just downloads the mini_installer to that dir and then executes it. For Chromium/Thorium builds, all you gotta do is double click it. 

If you are worried about timestamps or a downloader messing with the file, simply download the latest one from here with an existing browser instance.

**Comment by Alex313031** [comment]
@Intellectual234 David is this you. lol
