### ISSUE TITLE
Thorium vs  ungoogled-chromium [Test Speed at start new unkown page]

### ISSUE THREAD

**Issue by Milor123** [Alex313031/Thorium-Win#39]
Hi guys, I've tested the **Thorium** and **Thorium_AVX2** VS the my **ungoogled-chromium**  (With hardware Aceleration enable)
**My pc specs are:**
- Windows 11 (I try add the windows 8 compatibility mode to the Thorium builds)
- Intel Core i7 4790k (Lastest drivers)
- AMD Rx 6750 xt (Updated drivers)
- 32 GB DDR3 Corsair 1600Hz 

for both i get this result on GPU flag:
![image](https://user-images.githubusercontent.com/14153649/228318206-e63716a7-813d-49fa-9e6f-623720a678db.png)

I would know how can i solve the slow start, i am not sure if is it a bug... or dont know, see by your self:
Note: Thorium stay using my profile of ungoogle-chromium but its restore to default flags settings

Left is THORIUM ------------------------------- Right is ungoogled-chromium

https://user-images.githubusercontent.com/14153649/228317568-c562eec4-d343-4a2a-8b1d-c9c2ce5a6587.mp4

What should I do for solve this?, why its very slow like my firefox?
PD: Question, what build should I use, Thorium_AVX2 or Thorium? Considering that my processor i7 4790k  and GPU

**Comment by gz83** [comment]
> Hi guys, I've tested the **Thorium** and **Thorium_AVX2** VS the my **ungoogled-chromium** (With hardware Aceleration enable) **My pc specs are:**
> 
> * Windows 11 (I try add the windows 8 compatibility mode to the Thorium builds)
> * Intel Core i7 4790k (Lastest drivers)
> * AMD Rx 6750 xt (Updated drivers)
> * 32 GB DDR3 Corsair 1600Hz
> 
> for both i get this result on GPU flag: ![image](https://user-images.githubusercontent.com/14153649/228318206-e63716a7-813d-49fa-9e6f-623720a678db.png)
> 
> I would know how can i solve the slow start, i am not sure if is it a bug... or dont know, see by your self: Note: Thorium stay using my profile of ungoogle-chromium but its restore to default flags settings
> 
> Left is THORIUM ------------------------------- Right is ungoogled-chromium
> 
> What should I do for solve this?, why its very slow like my firefox? PD: Question, what build should I use, Thorium_AVX2 or Thorium? Considering that my processor i7 4790k and GPU

@Milor123 

You can use avx, avx2, sse3 versions.  But it should be noted that the version after M109 no longer guarantees the support of win7/8/8.1.

In addition, I would like to confirm that the version numbers of the two browsers and whether the usage conditions of the two browsers are as consistent as possible during the test?

**Comment by gz83** [comment]
> > > Hi guys, I've tested the **Thorium** and **Thorium_AVX2** VS the my **ungoogled-chromium** (With hardware Aceleration enable) **My pc specs are:**
> > > 
> > > * Windows 11 (I try add the windows 8 compatibility mode to the Thorium builds)
> > > * Intel Core i7 4790k (Lastest drivers)
> > > * AMD Rx 6750 xt (Updated drivers)
> > > * 32 GB DDR3 Corsair 1600Hz
> > > 
> > > for both i get this result on GPU flag: ![image](https://user-images.githubusercontent.com/14153649/228318206-e63716a7-813d-49fa-9e6f-623720a678db.png)
> > > I would know how can i solve the slow start, i am not sure if is it a bug... or dont know, see by your self: Note: Thorium stay using my profile of ungoogle-chromium but its restore to default flags settings
> > > Left is THORIUM ------------------------------- Right is ungoogled-chromium
> > > What should I do for solve this?, why its very slow like my firefox? PD: Question, what build should I use, Thorium_AVX2 or Thorium? Considering that my processor i7 4790k and GPU
> > 
> > 
> > @Milor123
> > You can use avx, avx2, sse3 versions. But it should be noted that the version after M109 no longer guarantees the support of win7/8/8.1.
> > In addition, I would like to confirm that the version numbers of the two browsers and whether the usage conditions of the two browsers are as consistent as possible during the test?
> 
> Should I configure something special on flags for my current specs? @gz83
> 
> Versions uses for this test are
> 
> * Thorium_AVX2_111.0.5563.111 (With my Data and reset flags and alsoe without reset flags)
> * Thorium_111.0.5563.111 (With my Data and reset flags and alsoe without reset flags)
> 
> Search and open a random page (A page that never has been open in my browsers), and in all test the results is the same, Thorium is slow for start to charge the page.
> 
> sse3 should be better for me?

@Milor123 

I personally think that when testing different browsers, you should control variables as much as possible (such as the number of open tabs, whether the feature flag is enabled, whether the tab is playing audio or video, etc.).  

Also, I see you are using win11 system, Thorium is compatible with win11 system, I am curious why you need to set the compatibility mode of win8?

According to the instruction set support of your processor, you can use the avx2 version at the highest, and you can also use the avx and sse3 versions.

**Comment by Milor123** [comment]
> @Milor123
> 
> I personally think that when testing different browsers, you should control variables as much as possible (such as the number of open tabs, whether the feature flag is enabled, whether the tab is playing audio or video, etc.).
> 
> Also, I see you are using win11 system, Thorium is compatible with win11 system, I am curious why you need to set the compatibility mode of win8?
> 
> At the same time, I also want to know what version number of ungoogled-chromium you are using, is there a win8 compatibility mode configured?
> 
> According to the instruction set support of your processor, you can use the avx2 version at the highest, and you can also use the avx and sse3 versions.

I've test the both browser in the same conditions, the sames flags, with diferents flags, with win8 compability mode, wihout it, and always get the same result, i thought that its a bug for my old procesor, but i am not sure (In general try many things and flags try know why happends it.)

My Degoogle-chromium version is 111.0.5563.116 (And is NOT using compatibility mode)
![image](https://user-images.githubusercontent.com/14153649/228395837-7d56bedd-e963-4423-8787-b79b6a6236bd.png)

Ohh okay **avx2**  its for me. (It was my first selection xD)

Thank you very much guys, and what should i do now? XD

**Comment by Alex313031** [comment]
@gz83 @goodusername123 This is strange. I am not getting this effect on my main machine or my HP machine which also happens to have 4790k and 32gb 1600 ram.

**Comment by Milor123** [comment]
> @gz83 @goodusername123 This is strange. I am not getting this effect on my main machine or my HP machine which also happens to have 4790k and 32gb 1600 ram.

Understand bro, What do you suggest me for try help to found the problem? I try it in CLEAN new portable build, but have the same problem.

**Comment by Alex313031** [comment]
@Milor123 The win8 compat mode thing is no longer needed.  We fixed that bug
Try with that, and clean profile with no flags.

**Comment by Milor123** [comment]
> @Milor123 The win8 compat mode thing is no longer needed.  We fixed that bug
> Try with that, and clean profile with no flags.

Understand, yesterday try use a clean install, without profile, original flags, the results is the same dont understand about why... :/, do you need some log file or something ?
