### ISSUE TITLE
Cannot use live caption at 100th

### ISSUE THREAD

**Issue by wilson818** [Alex313031/Thorium-Win#4]
could you solve this?

I run the /bin/chorme.exe, it cannot load live caption.

**Comment by Alex313031** [comment]
@wilson818 Do you not use the portable .bat? If you just run the exe, it will store your user profile data in %APPDATA%\Local\Chromium, rather than in the USER_DATA folder in the portable zip.

As far as live caption, I have not tested that with M100, but have used it with M98. None of my patches should mess with that, so this is likely an upstream thing. I will test with the next release, and get back to you here.

Otherwise, is Thorium working okay for you?

**Comment by Alex313031** [comment]
@wilson818 Try latest release. And if you are using portably, use the .bat. Otherwise use the installer.

**Comment by Alex313031** [comment]
@wilson818 hows is live caption coming?

**Comment by wilson818** [comment]
> 



> @wilson818 Try latest release. And if you are using portably, use the .bat. Otherwise use the installer.

I can't use AVX2， I only can use AVX.

I have tried M100.0.4848.0 with installer, it is the same, Live Caption could not be used...

**Comment by Alex313031** [comment]
@wilson818 Ok. Next release coming tomorrow, and will be a normal AVX release.

**Comment by wilson818** [comment]
> @wilson818 Ok. Next release coming tomorrow, and will be a normal AVX release.

I am using 100th 4888 with AVX, all things are well but Live Caption still does not work. 

I have tried it on another windows11 computer, but the same result.

**Comment by Alex313031** [comment]
@wilson818 I actually found in the code where it only will compile SODA (needed for live caption) if the CPU is detected as having sse4.1. I'm thinking since these builds are AVX or AVX2 that might have caused it. I made the commit to thorium, and next build I will test and you can test as well.
I knew that live caption worked on a vanilla build of Chromium, so I searched the entire Thorium codebase with a program that searches file contents, not just names, and searched for things like "live" "caption" "live caption" "soda" and "SODA" and read through them and that's how I found this. Can't guarantee it will fix it but it looks promising.

**Comment by Alex313031** [comment]
@wilson818 New release here and in the AVX2 repo.

**Comment by Alex313031** [comment]
@wilson818 How's it coming.

**Comment by wilson818** [comment]
> @wilson818 How's it coming.

I have tried 101st and 102nd which are AVX editions, but the live caption still could not be shown.

**Comment by wilson818** [comment]
> @wilson818 How's it coming.

I have good news to tell you, the live caption on 102.0.4973 may be working but not shown! 

When I turn on the live caption on it, the CPU is using 30-40% on Thorium, but when I turn it off, it's 10-20%.

I think the floating windows of the live caption were not shown, maybe you just need to fix this little problem.

**Comment by Alex313031** [comment]
@wilson818 Are you using google sync?

**Comment by wilson818** [comment]
> @wilson818 Are you using google sync?

yes, I am using Google sync. but on another computer without using google sync, the effect of live caption in Thorium is the same so far.

**Comment by Alex313031** [comment]
@wilson818  Wdym you're using google sync, but on another computer without using it?

I think Live Caption uses online translation which would use the same API as "translate this page" 

API Keys are needed for more than just sync, the API Keys bundled in Thorium have quotas for the sync api, translation api, geotagging api, google drive api, and others. You might try enabling sync in Thorium and see if it fixes it

**Comment by wilson818** [comment]
> @wilson818 Wdym you're using google sync, but on another computer without using it?
> 
> I think Live Caption uses online translation which would use the same API as "translate this page"
> 
> API Keys are needed for more than just sync, the API Keys bundled in Thorium have quotas for the sync api, translation api, geotagging api, google drive api, and others. You might try enabling sync in Thorium and see if it fixes it

I tried Google Chrome, it could use Live Caption when I don't log in a google account.

I had enabled sync in Thorium, and the live caption and translation could not be used.(in Google Chrome, the translation icon is on the address box when I am surfing a Spanish or French page)

**Comment by Alex313031** [comment]
@wilson818 Did you add yourself to that Google group?

**Comment by wilson818** [comment]
> @wilson818 Did you add yourself to that Google group?

[https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts](url)

Is this group? I've been joined. 

but it said: You don't have permission to access this content

**Comment by Alex313031** [comment]
@wilson818 Thats ok, as long as you're joined.
So sync is working for you, but NOT translate or live caption?

**Comment by wilson818** [comment]
> @wilson818 Thats ok, as long as you're joined. So sync is working for you, but NOT translate or live caption?

I've joined it last year (it showed me I joined it in 2021), now no translation, no live caption.   >_<

**Comment by Alex313031** [comment]
@wilson818 Try to unjoin, then re join.

**Comment by wilson818** [comment]
> @wilson818 Try to unjoin, then re join.

I've unjoined and then re-join, the live caption and translate are still no show...

**Comment by Alex313031** [comment]
I can translate pages just fine, is that what you're referring to?

Live Caption though, I can confirm this is an issue on Windows and Linux Thorium builds.

**Comment by wilson818** [comment]
the previous post was talking about runing chrome.exe directly in the folder of your build.

but if I run Thorium.bat, it could not got translate pages.

**Comment by Alex313031** [comment]
@wilson818 thats interesting and strange. Glad you got it working though.

**Comment by Alex313031** [comment]
@wilson818 When you run chrome.exe directly, it uses the normal profile directory, similar to if you had installed it. The thorium.bat is designed to disable logging, disable default browser check, and to create and use a user profile dir in the same folder it is located in, in the USER_DATA folder. You might try deleting the contents of that folder, and then just copying the contents of C:\Users\$USERNAME\AppData\Local\Chromium\User Data into it.

**Comment by wilson818** [comment]
> @wilson818 When you run chrome.exe directly, it uses the normal profile directory, similar to if you had installed it. The thorium.bat is designed to disable logging, disable default browser check, and to create and use a user profile dir in the same folder it is located in, in the USER_DATA folder. You might try deleting the contents of that folder, and then just copying the contents of C:\Users$USERNAME\AppData\Local\Chromium\User Data into it.

thank you .  and I can only use 100th with thorium.bat because 101st and 102nd are with bugs on Windows11

**Comment by Alex313031** [comment]
@wilson818 See note in latest releases. > https://github.com/Alex313031/Thorium-Win/releases/tag/M102.0.4973.0

"NOTE: There is an upstream bug in Chromium. It only appears on Windows 10/11. Windows 7/8/8.1 are fine.
Problem: You may get a condition when launching where extensions will not start and open tabs will say "RESULT_CODE_MISSING_DATA" or "STATUS_STACK_BUFFER_OVERRUN".
To fix this: Right click the Thorium shortcut, or the actual executable at C:\Users\USERNAME\AppData\Local\Chromium\chrome.exe , go to properties, and set the compatibility mode to windows 7 or 8."

**Comment by wilson818** [comment]
> @wilson818 See note in latest releases. > https://github.com/Alex313031/Thorium-Win/releases/tag/M102.0.4973.0
> 
> "NOTE: There is an upstream bug in Chromium. It only appears on Windows 10/11. Windows 7/8/8.1 are fine. Problem: You may get a condition when launching where extensions will not start and open tabs will say "RESULT_CODE_MISSING_DATA" or "STATUS_STACK_BUFFER_OVERRUN". To fix this: Right click the Thorium shortcut, or the actual executable at C:\Users\USERNAME\AppData\Local\Chromium\chrome.exe , go to properties, and set the compatibility mode to windows 7 or 8."

It could not be remembered by win11, it needs to be set the compatibility every time for running.

**Comment by Alex313031** [comment]
@wilson818 The thorium install dir has changed and i was slightly incorrect in my instructions.

Go to
C:\Users\USERNAME\AppData\Local\Thorium\chrome.exe

Right click, go to properties, then the compatibility tab, then click the "change for all users" button, and set to win 7 or 8 for all users.

**Comment by Alex313031** [comment]
@wilson818 Compatibility mode issue has been fixed for a while now, and live caption should also be working. Try latest release.

**Comment by wilson818** [comment]
> @wilson818 Compatibility mode issue has been fixed for a while now, and live caption should also be working. Try latest release.

yes, I can run your building without Compatibility mode now. And are you meaning the M106 is working with live caption?

 I didn't see the release of M106 with AVX1. Could you release M106 ?

**Comment by Alex313031** [comment]
@wilson818 Oh sorry, I forgot to upload it yesterday lol.

**Comment by Alex313031** [comment]
@wilson818 Other NTP page and search settings bugs have been fixed! New bug free M106 release > https://github.com/Alex313031/Thorium-Win/releases/tag/M106.0.5219.0

**Comment by Alex313031** [comment]
@wilson818 Is your original issue fixed? This issue is getting stale, and if I don't get a reply in another ~month I will be closing it. Feel free to reopen if you see this and it is closed and it isn't fixed.

**Comment by Alex313031** [comment]
@wilson818 Try latest release > https://github.com/Alex313031/Thorium-Win/releases/tag/M109.0.5362.0 I am closing this issue though because it had become stale.
