### ISSUE TITLE
Thorium 109 AVX build crashes even though cpu supports AVX

### ISSUE THREAD

**Issue by pritkr** [Alex313031/Thorium-Win#42]
![image](https://user-images.githubusercontent.com/81620727/231459054-1a2f5e61-5622-481d-9126-07ccf7d39f71.png)
![image](https://user-images.githubusercontent.com/81620727/230911114-19b2ec23-dffa-48f2-88ea-c19d004de940.png)
My Windows 7 system supports AVX but any AVX build of thorium doesn't work and crashes.
A blank windows appears but it crashes immediately.
I am a little noob so how can I give you more information to debug for example logs, crash reports etc?

**Comment by gz83** [comment]
> ![image](https://user-images.githubusercontent.com/81620727/231459054-1a2f5e61-5622-481d-9126-07ccf7d39f71.png) ![image](https://user-images.githubusercontent.com/81620727/230911114-19b2ec23-dffa-48f2-88ea-c19d004de940.png) My Windows 7 system supports AVX but any AVX build of thorium doesn't work and crashes. A blank windows appears but it crashes immediately. I am a little noob so how can I give you more information to debug for example logs, crash reports etc?

@pritkr 

Duplicate: #47
