### ISSUE TITLE
Sync (Google Sync / Profile Sync) missing on clean portable version (.zip) M111.0.5563.111 WIN64

### ISSUE THREAD

**Issue by maxwowpow** [Alex313031/Thorium-Win#43]
Used a portable version with flags 
--disable-encryption --disable-machine-id 

In the latest version there is no sync / login function.

On MAC it works (no extra flags)

Vanilla extracted from .zip. Started THORIUM.BAT

Not sure to had seen somewhere, that sync works when encryption enabled? b. On windows no sync possible c. API keys changed or smth?

UPD:
There is an **avx2 build**, so if you've a modern cpu, give that a try:
https://github.com/Alex313031/Thorium-AVX2/releases

**Comment by k3bc999** [comment]
It looks like the latest version (M111.0.5563.111) does not include Google Sync

**Comment by gz83** [comment]
@maxwowpow @k3bc999 

Local testing does not replicate the problems you encountered.

Please try to remove `-disable-encryption` and `-disable-machine-id` before trying to use the related features.

**Comment by gz83** [comment]
@maxwowpow 

I'm using Win11 x64, also, this version of Thorium was compiled by me and we have tested it before releasing it.
Please try uninstalling the browser and reinstalling it, then try using the sync feature again.

**Comment by gz83** [comment]
Has the path to the user data folder inside the THORIUM.BAT file been modified?

Also, is it convenient to provide a screenshot of the top right corner of the main interface and a screenshot of the chrome://settings/people page?

**Comment by gz83** [comment]
@maxwowpow 

Sync is available on my end, you can check the other issue I linked to inside this one.

Also, the thorium development team is preparing to update the repo to version M112, and we will investigate this issue during the update process.

**Comment by Alex313031** [comment]
@maxwowpow @k3bc999 Sorry guys, I actually forgot to put the API Keys in for that build. ANyway, the latest builds should have sync working.

However, note that the --disable-encryption seems to break sync because of security reasons. You don't want your google credentials just sitting in a plaintext file.
