### ISSUE TITLE
M111.0.5563.111 doesn't include Google Services

### ISSUE THREAD

**Issue by PR0LAPSE** [Alex313031/Thorium-Win#44]
M111.0.5563.111 doesn't include Google Services (Google Translate, Google LogIn, Google Sync, etc).
I had to roll back to a previous working release: https://github.com/Alex313031/Thorium-Win/releases/tag/M110.0.5481.178

**Comment by gz83** [comment]
@PR0LAPSE 

Local testing did not reproduce the problem you encountered, are you using the portable version or the mini_installer version?

**Comment by gz83** [comment]
@PR0LAPSE 

Close the browser completely, then empty the USER_DATA folder (if you have important data, please backup it first) and run THORIUM.BAT again to see if you can use sync and upload screenshots again

**Comment by gz83** [comment]
@PR0LAPSE 

The thorium development team is preparing to update the repo to version M112, and we will investigate this issue during the update process.

Also, are the problems you are experiencing similar to the ones this person is experiencing?

**Comment by gz83** [comment]
@PR0LAPSE 

The problem may not be related to portable edition and needs further investigation.

Please stay tuned to #43 for more progress, this issue will be closed later because it is a similar issue.
