### ISSUE TITLE
Error installing Thorium Win7 Maintenance release in my old pc

### ISSUE THREAD

**Issue by godwyn09** [Alex313031/Thorium-Win#45]
The latest version of Thorium for Windows 7 right now is 109.0.5414.139. It gives me error like this in my screenshot. I tried some troubleshooting like uninstall the 109.0.5414.120 release and trying to install the 109.0.5414.139. My PC doesnt support AVX2 and AVX but SSE3 and SSE2 does. Here are my PC specs. 
AMD Athlon X2 240 
Nvidia Geforce 6150se Nforce 430
4GB of ram

![image](https://user-images.githubusercontent.com/130208402/233825270-f3d540b8-6cda-46dc-9cc6-eaad3cb989e5.png)

**Comment by gz83** [comment]
@godwyn09 

Sorry, we do not have a version of the SSE3 instruction set for this release

**Comment by Alex313031** [comment]
@gz83 We do have an SSE3 version for this! @godwyn09 > https://github.com/Alex313031/thorium-win7
