### ISSUE TITLE
Bulids For XP (NT 5.1) SP3?

### ISSUE THREAD

**Issue by MWF2** [Alex313031/Thorium-Win#46]
i saw of you did make browser support for 7, 8 and 8.1, but question is, when you going to bulid that browser for xp sp3 like 109 version same like you did to 7, 8, 8.1 or something? cuz there other browser like mypal, it takes while of developing, and other people don't want to use chinese chromium, but since i saw of your project about for 7, 8 and 8.1, that's nice project to keep 7, 8 and 8.1, there site of documentation of newer chromium for xp, the documentation is made by discord guy name 030_Nayan猫 Or (andreiixe/Andrei Alexandru) from github (note: i copy everything and pasted it from notepad since site one it required created account, but here if you interested to read)
[chromium newer for xp.txt](https://github.com/Alex313031/Thorium-Win/files/11368244/chromium.newer.for.xp.txt)

Thank you

**Comment by gz83** [comment]
@MWF2 

I think it is unrealistic to try to support the XP system again at this stage, which may not bring much benefit.

**Comment by MWF2** [comment]
there good reason for this, 1st: nobody will have to download and use one-core api, because one core api is buggy, it will cause bsod if try to install it, and 2nd: no one will use chinese version of chromium anymore, there chinese chromium that works with xp like extreme explorer 360, but issue is, some people don't want to use it, and even on windows xp discord server, they want to non chinese chromium fork that works for xp
> @MWF2
> 
> I think it is unrealistic to try to support the XP system again at this stage, which may not bring much benefit.

**Comment by gz83** [comment]
Now the network technology is very different from the xp era, xp system in the present has not been able to adapt to the current network environment, non-special circumstances, we should not be too obsessed with it, and if you need browser support XP system, it may need to use some very old branch for development.

At this stage, I think it is more meaningful to continue to try to support win7/8/8.1 system than to try to support xp system. Also, thorium has more modifications, and these modifications are not necessarily suitable for xp systems. @MWF2

**Comment by Alex313031** [comment]
@gz83 The absolute latest Chromium version that anyone has gotten running on XP is 102, from 360 Browser in China.

The next latest is 69, from Maxthon browser.

And the next latest is Advanced Chromium, based on 54

49 was the last to officially support winxp and server 2003

10 was the last to support win 2000

All of the above browsers are closed source, so I have no idea how they got them running on xp.

One core api is indeed buggy. Have you looked into mypal, and the new mypal based on firefox 68?
I know its not chromium, but.
