### ISSUE TITLE
M112.0.5615.166 thorium.bat

### ISSUE THREAD

**Issue by hyunsun1004** [Alex313031/Thorium-Win#47]
Latest zip extracted to usb with W10 22H2 on home PC thorium.bat with the appended --disable-encryption --disable-machine-id works fine. (I have Brave and Firefox installed, but no Edge. Defender has also been disabled on this machine and no AV is actively scanning.)

However, on a work PC W10 20H2, clicking on thorium.bat throws an error. (I can't remember the code, as it flashed with a message in Korean and disappeared.) Removing the two portability flags from thorium.bat didn't solve it. Also, the file extension .bat disappears completely, like it's being disabled by something in the background. I tried starting the browser from the BIN folder, but got the same error. I even tried extracting the zip again (on my USB) on the work PC and starting fresh. Unfortunately, thorium will not open on this work PC, and it would be useful if I had the exact error code. Sorry for not having the error code.

The work PC has outdated versions of Chrome browser and Edge preinstalled. Defender is active but real-time protection has been turned off. Since it's a work PC, I can't really mess with it - like crippling Defender. Every time the PC is restarted, W10 returns to its original install state.

There's not much to go on as to why it works at home and not at work. It's possible that Defender, the office network, or the presence of Chrome may be interfering with Thorium. That said, I really like the browser, but I need its portability at work more than at home. Cheers for the hard work though.

**Comment by gz83** [comment]
Are you comfortable providing information about your processor?

@hyunsun1004

**Comment by hyunsun1004** [comment]
I don't know the processor on the work PC other than it's a weak Intel with integrated graphics. The error code is 0xc0000142, and the bat extension is automatically being disabled.  The application in the BIN folder gives the same error code. Should I try the AVX2 version instead?  Maybe it's an older chip.

**Comment by gz83** [comment]
You can try the following process to see which processor your computer is using

https://www.howtogeek.com/413942/how-to-see-what-cpu-is-in-your-pc-and-how-fast-it-is/

@hyunsun1004

**Comment by hyunsun1004** [comment]
There's a security measure in place disabling the bat. It's a work PC, so it's back to Brave Portable on a USB stick for me, since it works.  I just thought I'd try something different, but Thorium portable isn't the answer for my use case ATM. Thanks for the replies.
