### ISSUE TITLE
Netflix not working

### ISSUE THREAD

**Issue by MulverineX** [Alex313031/Thorium-Win#48]
All the tests for Widevine pass, except when I try to view Netflix it errors out. 

https://help.netflix.com/en/node/61874?accordionCategory=windows_computer

**Comment by MulverineX** [comment]
@Alex313031 Same as OP on the AVX2 issue

**Comment by MulverineX** [comment]
Also doesn't work on version 113

**Comment by gz83** [comment]
![image](https://github.com/Alex313031/Thorium-Win/assets/17492865/773d0cc4-5b97-4075-97b1-c3609b50df46)

Please open the chrome://flags page and open the three experimental flags shown in the image to see if it solves the problem you are experiencing.

@MulverineX

**Comment by MulverineX** [comment]
Didn't do anything, tried clearing the site data too.

**Comment by Alex313031** [comment]
@MulverineX Thanks for using Quark Player. Feel free to make an issue for any suggestions.

However, M114 should fix this.

**Comment by MulverineX** [comment]
Waiting on a build to test

**Comment by Alex313031** [comment]
@MulverineX 114 is released.

**Comment by MulverineX** [comment]
@Alex313031 just tried it, thorium doesn't start, just like the avx2 release

**Comment by Alex313031** [comment]
@MulverineX Ugh. Gonna test in a win10 and win11 vm with both the avx and avx2 versions.

**Comment by Alex313031** [comment]
@MulverineX @gz83 Upon further investigation, it seems that Google and some streaming sites have tightened their restrictions with widevine, now requiring VMP (Verified Media Path) which requires signing, something that costs way too much for me.

See this issue where I explain this further > https://github.com/Alex313031/Thorium-AVX2/issues/84

However, this is not something on Thorium's end. Many sites using Widevine still work. Hulu and Apple Music worked for me. Netflix, however, did not.
