### ISSUE TITLE
Tab bar goes blank if a tab favicon updates while the browser is minimized

### ISSUE THREAD

**Issue by Delphox** [Alex313031/Thorium-Win#49]
**System Details**
 - OS: Windows 10
 - Thorium Version 112.0.5615.166

**Problem**
Tab bar goes blank if a tab favicon updates while the browser is minimized. Goes back to normal if I click the + button, change window size or switch tab with the dropdown icon. Very annoying with messaging apps like Discord or Whatsapp Web that update the favicon to reflect unread state and count pings.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/5883538/f4e79945-d6f8-42d1-8514-fb6646b96a9e)

https://github.com/Alex313031/Thorium-Win/assets/5883538/0794945e-99b3-42ad-adaa-7f96a598e806

**Additional Notes**
Clicking the + to add a new tab, or maximizing/restoring the window fixes it, until it happens again. It's also possible to replicate less consistently by opening an uncached website and immediately minimizing (such as using Win+D).

**Comment by gz83** [comment]
It's possible that the double-click to close tabs patch introduced this error.

Also, I'd like to ask if you were able to encounter this error on the 112 version of stable chrome?

@Delphox

**Comment by Delphox** [comment]
> Did you turn on the double-click to close tabs flag?
Nope, I've never turned it on. I also tested on a fresh install, and both on regular AVX and AVX2 and encountered it.

>Also, I'd like to ask if you were able to encounter this error on the 112 version of stable chrome?
Nope, doesn't happen on regular stable chrome 112.

Also here's a website that makes testing it easier: https://www.favitimer.com/ set the timer to a few seconds then minimize it and restore when it starts beeping, and it should happen.

**Comment by gz83** [comment]
@Delphox 

Thanks for reporting this issue, I will look into it.

**Comment by Delphox** [comment]
Only the ones in the portable .bat

`START "" "%cd%\BIN\thorium.exe" --user-data-dir="%~dp0%\USER_DATA" --allow-outdated-plugins --disable-logging --disable-breakpad --enable-experimental-web-platform-features --new-canvas-2d-api --disable-machine-id --disable-encryption`

**Comment by gz83** [comment]
@Delphox 

thanks for more information

**Comment by Aedon** [comment]
Thanks for mentioning tab scrolling, @gz83. 
Enabling tab scrolling (any option) fixed this problem for me in avx2. And this feature is not bad to have lol.

**Comment by Delphox** [comment]
Good find @Aedon, I can confirm the invisible tab problem disappears with Tab Scrolling, however that creates another problem where dragging a tab out of a window crashes the whole browser (tested on AVX2 which I run as daily driver, idk if it happens on mainline as well). But at least this makes it easier to pinpoint where the bug is.

**Comment by Aedon** [comment]
You're right @gz83 ,  I had forgotten about that bug.

**Comment by Delphox** [comment]
Updated to Thorium 114 AVX2 yesterday (I skipped 113 due to needing HEVC support) and it seems this issue is fixed! Thanks for the great work Thorium team!
