### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by ritmation** [Alex313031/Thorium-Win#5]
For some reason, latest build of Thorium for Windows (M100.0.4848.0) uses a yellow icon with an exclamation sign ![image](https://user-images.githubusercontent.com/26736051/151796752-8cbed8a6-c480-4e07-956b-4ae4c5e2eeff.png)
instead of the usual chromium icon (blue circle).
It's not a big of a deal, but it's slightly annoying, makes me think that something is wrong, when, in fact, everything is okay.

**Comment by Alex313031** [comment]
@ritmation I noticed this too. Seems to be an upstream thing. Latest releases doesn't have this.

**Comment by Alex313031** [comment]
@ritmation Latest release still has this issue. Looking into maybe if its something on my end, as RobRich's release doesn't have this, and his was M100.0.4863.0 vs my latest which is M100.0.4865.0.

**Comment by Alex313031** [comment]
@ritmation I am looking into a fix, and am compiling as we speak to see if it fixes it. Also posted a notice in my latest releases about this.
Besides this, how do you like Thorium so far?

**Comment by ritmation** [comment]
I like it. It's stable and fast, and I started using it on a daily basis. Thank you and keep up the good work.

**Comment by Alex313031** [comment]
@ritmation FINALLY fucking fixed the icon issue. Took may too much work.

**Comment by ritmation** [comment]
Thank you. I'm closing this issue.
