### ISSUE TITLE
Cant install Thorium-Win on ZorinOS/Linux using WINE

### ISSUE THREAD

**Issue by Username23453** [Alex313031/Thorium-Win#50]
See screenshot:
![12232e3e3](https://github.com/Alex313031/Thorium-Win/assets/105397593/7e4464fe-1fb4-4711-87ef-27830e0351d4)

This might help solve problem:
https://forum.winehq.org/viewtopic.php?t=34839

**Comment by gz83** [comment]
@Intellectual234 

It is not recommended to run thorium in wine, if you really want to run thorium in wine, you need to pay attention to whether thorium is compatible with wine

**Comment by Intellectual234** [comment]
@Ho, yeah i know, but I'm trying to get IDM(Internet download manager) to work with my ZorinOS. Have u used IDM before?

**Comment by gz83** [comment]
@Intellectual234 

Please note that if you want to @ me inside github, please @gz83.

I have only used IDM on windows, I have not used IDM in linux or wine

**Comment by Intellectual234** [comment]
@ho, i know it wasnt going to tag you. :)  what is your main OS that you use?

**Comment by gz83** [comment]
@Intellectual234 

I mainly use windows, but I also use debian and ubuntu.

It should be noted that I use debian and ubuntu to cross-compile Thorium/Chromium for windows.

**Comment by Intellectual234** [comment]
I like windows design a lot, its much better & smoother than ubuntu/zorin. But windows has tons of spyware, bloatware & tracking telemetry. & there is no way to block it or remove it, as it gets re-installed after every update. & also if you block it via firewall, it causes malfunctions where RAM & CPU become high, get used up, a spiral. I know of no solution.
Perhaps you would like to help figure out how to use IDM in ubuntu/Zorin.

**Comment by Intellectual234** [comment]
@SoulInfernoDE , thanks for the advice. unfortunately. Jdownloader has disadvantages. it doesnt actually integrate into the web browser, therefore it makes you tell it ur social media login info & cookies. Whereas IDM & XDM bypasses all of that. So Jdownloader is not what im looking for.

**Comment by Alex313031** [comment]
@Intellectual234 Running Chromium (or based browsers) on WINE has been hit and miss. Depending on WINE version, whether you have Wines optional C++ Mono framework and web engine installed, and Chromium version, it may or may not work. Also, often you have to pass the --disable-gpu cmdline flag to disable hardware acceleration in chromium to get it to work.
