### ISSUE TITLE
True Portable?

### ISSUE THREAD

**Issue by Nyanpasu1** [Alex313031/Thorium-Win#51]
I am trying to use portable option so i can use it on multiple machine wtihout need to backup registry and userdata on local :

START "" "%cd%\BIN\thorium.exe" --user-data-dir="%~dp0%\USER_DATA" --allow-outdated-plugins --disable-logging --disable-breakpad --enable-experimental-web-platform-features --new-canvas-2d-api --disable-encryption --disable-machine-id

So should i keep run the BAT file on every browser launch? or i just need to run it once and it is remain portable even i pin the browser on taksbar?

**Comment by gz83** [comment]
The main factors affecting portability are the following two parameters

--disable-encryption --disable-machine-id

After you use the above two parameters to open the browser once, the browser will generate portable personal data. After the generation is complete, you need to remove these two parameters to avoid affecting your cookie and other data.

The above two parameters have been tested in the previous version, they are available, and the personal data generated can also be freely migrated.

@Nyanpasu1

**Comment by gz83** [comment]
I'd prefer this to be fixed upstream (chromium codebase)

@Alex313031 @Nyanpasu1

**Comment by A81N9** [comment]
> i see, so i need to keep run the BAT file on every browser launch which means i cannot set this browser as default browser, automatically open link to this browser by default, or pin to taskbar means it will open new profile without those flags instead and will void all my data.我知道，所以我需要在每个浏览器启动下运行BAT文件，这意味着我无法将此浏览器设置为默认浏览器，默认情况下会自动打开到此浏览器的链接，或者对Taskesbar的PIN表示，它将无需这些标志即可打开新的配置文件，并且会使我的所有数据失散。
> 
> wish there is easy way to fix this issue...希望有简单的方法可以解决此问题...

@Alex313031 @gz83 
I have the same question.
I start with the bat file every time, but it cannot be used as my default browser. In some scenarios where the browser is automatically started, a new configuration file will still be recreated.
