### ISSUE TITLE
Thorium crashes when creating profile

### ISSUE THREAD

**Issue by jstdk** [Alex313031/Thorium-Win#58]
**System Details**
 - OS: Windows 11
 - Thorium Version M114.0.5735.134

**Problem**
Thorium crashes when trying to create a new profile (click + Add in screenshot), while the same action works on the latest version of Chromium

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/115603308/903f986c-3561-47b0-8985-1fed9d6eed67)

**Comment by gz83** [comment]
Similar questions

https://github.com/Alex313031/Thorium-AVX2/issues/95

**Comment by jstdk** [comment]
Thanks @gz83, I missed that one!

**Comment by Alex313031** [comment]
@gz83 @jstdk Fixed with latest M115
