### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by trimechee** [Alex313031/Thorium-Win#60]
Hello, I went to my windows 10 firewall settings to see the authorized programs, I noticed that Chromium browser (the one used by Thorium browser ?) is authorized in the firewall even though I don't have a chromium browser but I noticed Thorium browser is not authorized in the firewall, is this normal and does Thoirum browser work normally without authorization in the firewall?

**Comment by Alex313031** [comment]
@trimechee Are you sure you dont have Chromium on your system at all. This will happen even if it is not installed, for example if you download a portable build or .zip of Chromium.

If you are completely sure, can you uninstall and then re-install Thorium. (You can choose to delete your user data or leave it alone, which is the default)

**Comment by trimechee** [comment]
Yes, I am sure i have no chromium installed, i installed chromium browsers from the woolyss site, I uninstalled them all in order to install Thorium browser and avoid possible conflicts....

I went to check, there are lots of software that I uninstalled and yet their authorizations in the firewall remained active, it's a bit strange that windows 10 is normally supposed to erase these authorizations from these uninstalled software... .

i just disabled the authorization in the firewall of chromium because i can remove chromium from the firewall, the "remove" button is grayed out and inactive, and so when Thorium needs authorization in the firewall, Thoirium will make a request of authorization that we will accept? or Thorium can run without firewall authorization? I see in the firewall there are 2 Thorium boxes in the firewall and the 2 boxes of Thorium are deactivated, should I activate them ?

**Comment by trimechee** [comment]
@gz83 Interesting, thank you ? there is 2 boxes named Thorium in firewall, and the boxes anr disables, shoud i remove these Thorium boxes without risk and when Thorium will need special authorization, Thorium will make a request to me or if we remove Thorium from the firewall, it Is final without possible return?

**Comment by gz83** [comment]
After deleting the rules of the windows firewall, the next time the program that triggers the rules requests an outbound or inbound request, the windows firewall should remind you again, and you can test it at will.

@trimechee

**Comment by trimechee** [comment]
Very very interesting and important ! so i will delete the 2 disabled Thorium boxes in firewall, thank you si much for your help @gz83 :) 💯

**Comment by trimechee** [comment]
@Alex313031 @gz83 Problem solved, I removed Thorium from the firewall then opened Thorium which immediately asked me to have permission via the firewall, thank you :)
