### ISSUE TITLE
bug when dragging a tab

### ISSUE THREAD

**Issue by ggauzin** [Alex313031/Thorium-Win#61]
**System Details**
 - OS: win11
 - Thorium Version Version 114.0.5735.205 (Official Build) (64-bit)

**Problem**
chashes when dragging a tab

**Screenshots**
https://github.com/Alex313031/Thorium-Win/assets/128216038/1d9ff9c0-117f-44d6-9456-3ba6522b7543

**Additional Notes**
happens only on latest

**Comment by Alex313031** [comment]
@ggauzin Other users are reporting this too. Only on Windows 11. Windows 10 seems fine.

**Comment by Alex313031** [comment]
@ggauzin Does M116 version still have this issue.

@gz83 I know you were able to reproduce this on your Win11 machine, but does it still occur?

**Comment by gz83** [comment]
I tested version 116 of thorium with fresh user data and found that this problem no longer exists

@Alex313031 @ggauzin

**Comment by ggauzin** [comment]
it does occur anyway
