### ISSUE TITLE
hijack protection

### ISSUE THREAD

**Issue by ggauzin** [Alex313031/Thorium-Win#62]
**Is your feature request related to a problem? Please describe.**
browser hijacking is shit, please add a feature to protect user from it by adding additional check on browser start-up

**Describe the solution you'd like, including relevant patches or source**
by making an additional check on browser start-up. On the install processor, motherboard, gpu and memory info must be loaded in the secured file. If on start up any of the info changed, secure all passwords and cookies ASAP, the user must log into his google account again to use the browser.

**Additional Notes**
yeah, i know that you can read all the cookies as the plain text somewhere in the files, but i am begging you, change that

**Comment by Alex313031** [comment]
@ggauzin Because of the way cookies and web workers are designed, changing how cookies are stored would break most sites. 

As far as doing a platform check on startup, IDK how to implement that.
