### ISSUE TITLE
Netflix and some videos play problem.

### ISSUE THREAD

**Issue by Dachoni03** [Alex313031/Thorium-Win#63]
Hello! When using Netflix the movies can't be played and some videos on YouTube.

**Comment by gz83** [comment]
Regarding the problem that netflix cannot be played, please see the following issue

https://github.com/Alex313031/Thorium-Win-AVX2/issues/84

Regarding the inability to play the video on YouTube, please give the link of the video that cannot be played

@Dachoni03

**Comment by Alex313031** [comment]
@gz83 Some videos on youtube use widevine. Specifically movies and stuff. Which are normally paid for individually, or available with a youtube premium subscription. However, sometimes youtube also offers free premium copyrighted content. In any case, content like this is protected with widevine. If youtube is requiring VMP to play these, then it will also not work for the same reasons outlined in the post you linked
