### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by gosndka** [Alex313031/Thorium-Win#64]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11] Windows 10 Pro 22H2
 - Thorium Version [e.g.107.0.5347.0] M115.0.5790.172

**Problem**
I downloaded the portable version and after extracting the zip file and running thorium bat, a popup appears unable to open, kindly do refer the below screenshot.

**Screenshots**
![Capture](https://github.com/Alex313031/Thorium-Win/assets/92586328/5261427b-1e2a-44e4-8f9f-5f71058a548c)

**Additional Notes**
Even after downloading the exe file and running it, nothing happens

**Comment by gz83** [comment]
What processor are you currently using?

@gosndka

**Comment by gosndka** [comment]
> What processor are you currently using?
> 
> @gosndka

Intel pentium g2020

**Comment by gosndka** [comment]
> The version in this repo uses the avx instruction set for compilation, and the processor you are using does not support the avx instruction set, so you cannot use the version in this repo, you need to use the SSE3 version
> 
> https://github.com/Alex313031/Thorium-Special/releases/tag/M110.0.5481.179-2
> 
> This version is an old version, the new SSE3 version needs to wait for the release of Alex313031
> 
> @gosndka @Alex313031

Okay, so I have to wait for the new update or continue using the official chrome?
And found out that you guys also made a fork of firefox called mercury and the same issue arises there too.... @gz83 @Alex313031

**Comment by Alex313031** [comment]
@gz83 Can we make an SSE3 version of M115? If you don't want to do it, I can do it, I am just building the Win7 releases right now.

**Comment by gz83** [comment]
> @gz83 Can we make an SSE3 version of M115? If you don't want to do it, I can do it, I am just building the Win7 releases right now.

I'm going to try to cross compile on an Ubuntu system later today

@Alex313031

**Comment by gz83** [comment]
> > The version in this repo uses the avx instruction set for compilation, and the processor you are using does not support the avx instruction set, so you cannot use the version in this repo, you need to use the SSE3 version
> > [Alex313031/Thorium-Special@`M110.0.5481.179-2` (release)](https://github.com/Alex313031/Thorium-Special/releases/tag/M110.0.5481.179-2)
> > This version is an old version, the new SSE3 version needs to wait for the release of Alex313031
> > @gosndka @Alex313031
> 
> Okay, so I have to wait for the new update or continue using the official chrome? And found out that you guys also made a fork of firefox called mercury and the same issue arises there too.... @gz83 @Alex313031

Mercury doesn't work on your computer for the same reason, we will consider compiling some SSE3 version for Mercury

@gosndka

**Comment by Alex313031** [comment]
@gosndka We are building a new SSE3 version of Thorium
Mercury is only compiled with AVX, so sorry there.

**Comment by gosndka** [comment]
> @gosndka We are building a new SSE3 version of Thorium Mercury is only compiled with AVX, so sorry there.

Why not? Any reason? also is there any eta for the thorium release for chrome

**Comment by Alex313031** [comment]
@gosndka Here you go sir > https://github.com/Alex313031/Thorium-Special/releases/tag/M115.0.5790.172-1

And simply because it takes a long time to build Thorium and Mercury, and I am already bogged down with builds. I might eventually make an SSE3 mercury release.

**Comment by gosndka** [comment]
> @gosndka Here you go sir > https://github.com/Alex313031/Thorium-Special/releases/tag/M115.0.5790.172-1
> 
> Thank @gz83 for taking the time to build this.
> 
> And simply because it takes a long time to build Thorium and Mercury, and I am already bogged down with builds. I might eventually make an SSE3 mercury release.

Oh I didn't mean it like that, sir just wanted to ask.
