### ISSUE TITLE
Enpass not visible in input fields

### ISSUE THREAD

**Issue by jankete** [Alex313031/Thorium-Win#65]
**System Details**
 - OS: Windows 11 
 - Thorium Version: 115.0.5790.172

**Problem**
I use the Enpass Browser Extension [from Chome Web Store](https://chrome.google.com/webstore/detail/enpass-password-manager/kmcfomidfpdkfieipokbalgegidffkal) for managing my passwords. In Chrome it is working fine with showing up matching entries in form fields (see screenshot below), in Thorium it is not. The settings for the extenstion are the same in both browsers

**Screenshots**
Chrome OK:
![image](https://github.com/Alex313031/Thorium-Win/assets/22338766/e74b3683-f5f9-45f1-a09f-46c49fb39102)

Thorium not OK:
![image](https://github.com/Alex313031/Thorium-Win/assets/22338766/aa4f6ff3-18b8-491f-af2a-98f25885cd12)

**Comment by Alex313031** [comment]
@jankete Are you by any chance using the portable .zip?

**Comment by jankete** [comment]
No. I'm using the mini installer.

**Comment by Alex313031** [comment]
@jankete No not to try it. Do you have experimental web platform features enabled via either command line or chrome://flags?

**Comment by jankete** [comment]
No, all is default there.

**Comment by gz83** [comment]
I think this is related to Enpass not being able to find the NativeMessagingHosts of the Thorium browser. You can check the Enpass documentation to see if there is a related solution.

@jankete

**Comment by jankete** [comment]
I started a [thread in the Enpass forum](https://discussion.enpass.io/index.php?/topic/29321-issue-on-enpass-extension-with-thorium-browser/). Maybe there will be some hints, if it's not an issue on Thorium side.
