### ISSUE TITLE
cant install thorium

### ISSUE THREAD

**Issue by mattdoot** [Alex313031/Thorium-Win#72]
**System Details**
 - OS: Windows 10 64 bit 22H2 Pro
 - Thorium Version N/A

**Problem**
trying to install thorium but nothing happens when i run installer. trying the zip/portable and running the exe gives error code 0xc0000142 which is a compatability error. trying compatability settings within file properties gives same error code. unsure whats causing. using windows 7 32 bit version works fine but gets an error saying "STATUS_ACCESS_VIOLATION" which means the 32 bit version of chromium is unstable.

**Screenshots**

![Screenshot_93](https://github.com/Alex313031/Thorium-Win/assets/89425464/a18f2ab5-99a1-475e-9add-fd805b88835b)
![Screenshot_58](https://github.com/Alex313031/Thorium-Win/assets/89425464/5535034c-b2d8-40dd-b83b-8cda72f59b26)

**Additional Notes**
not using a idm either, idek what that stands for, been downloading from github page

**Comment by gz83** [comment]
Questions about thorium-win7 need to be fed back in the thorium-win7 repo, we will soon provide a new version of thorium-win7 (the version number will be more than 109), the new version may solve the "STATUS_ACCESS_VIOLATION " crash.

Also, regarding your inability to open the thorium browser on win10, what processor are you currently using?

@mattdoot

**Comment by mattdoot** [comment]
processor is an intel celeron
![image](https://github.com/Alex313031/Thorium-Win/assets/89425464/1d671760-3195-4af5-9246-dd17e12c3d6c)

**Comment by gz83** [comment]
> processor is an intel celeron ![image](https://user-images.githubusercontent.com/89425464/276072211-1d671760-3195-4af5-9246-dd17e12c3d6c.png)

Please use the following version

https://github.com/Alex313031/Thorium-Special/releases/tag/M117.0.5938.157-1

@mattdoot

**Comment by mattdoot** [comment]
thank you
