### ISSUE TITLE
Udemy, Netflix, and NOWTV Video Error

### ISSUE THREAD

**Issue by Dormant-Hero** [Alex313031/Thorium-Win#73]
**System Details**
 - OS: Windows 10
 - Thorium Version 117.0.5938.157

**Problem**
An entire courses set of videos on udemy do not play and provide the below error. I test the same ones in firefox and it works fine. 

I think this is to do with the latest videos on udemy probably having some security in place to prevent dubious action. Not even sure how much this is worth reporting but just in case :).

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/79374258/aa8d46e8-4903-496e-8436-6227a65e7f75)

**Comment by lotek2k** [comment]
Got also a error on Netflix cant watch Movies ..

**Comment by gz83** [comment]
Does Chrome also have this problem? Also, does this site use widevine?

@Dormant-Hero

**Comment by gz83** [comment]
> Got also a error on Netflix cant watch Movies ..

The problem with netflix not playing is due to Thorium's inability to do VMP validation, and there's no good solution at the moment, other than paying a fee to widevine

@lotek2k

**Comment by Dormant-Hero** [comment]
I'll have a look when I'm home from work.

Please tell me what I would need to look for alternatively it may be easy and I will Google.

Thanks for getting back to me.

**Comment by gz83** [comment]
> I'll have a look when I'm home from work.
> 
> Please tell me what I would need to look for alternatively it may be easy and I will Google.
> 
> Thanks for getting back to me.

Please see my reply above

@Dormant-Hero

**Comment by gz83** [comment]
Thank you for providing more specific information.

Please see this reply: https://github.com/Alex313031/Thorium-Win/issues/73#issuecomment-1767566078

There is a high chance that the problem is caused by VMP verification.

@Dormant-Hero

**Comment by Dormant-Hero** [comment]
You are probably getting more issues reported than normal due to a youtube being made of this amazing browser. 

I guess this is a duplicate issue potentially with it being the same as the netflix one. Feel free to close if that helps organise or is the preferred choice and I can just watch the netflix one I guess.

**Comment by alcio1** [comment]
Same problem here with Udemy

**Comment by lotek2k** [comment]
> > Got also a error on Netflix cant watch Movies ..
> 
> The problem with netflix not playing is due to Thorium's inability to do VMP validation, and there's no good solution at the moment, other than paying a fee to widevine
> 
> @lotek2k

How much does it coast to verify the browser ?

**Comment by gz83** [comment]
> > > Got also a error on Netflix cant watch Movies ..
> > 
> > 
> > The problem with netflix not playing is due to Thorium's inability to do VMP validation, and there's no good solution at the moment, other than paying a fee to widevine
> > @lotek2k
> 
> How much does it coast to verify the browser ?
> 
> Does the AVX2 broweser version works on netflix and co ?

According to Alex, a fee of US$5,000 needs to be paid to Widevine on a regular basis, but I am currently unclear whether this fee is paid annually or monthly.

@lotek2k

**Comment by Dormant-Hero** [comment]
Regardless of monthly or annually that is a huge barrier of entry to having a complete web browser for all this DRM content. I doubt many know about this that use their web browsers every day like the world is all rainbows and butterflies. 

Thank you for the insight.

**Comment by Blazzycrafter** [comment]
> Regardless of monthly or annually that is a huge barrier of entry to having a complete web browser for all this DRM content. I doubt many know about this that use their web browsers every day like the world is all rainbows and butterflies.

This borders on anti-competitive abuse of market power.
sad

**Comment by Dormant-Hero** [comment]
I recently found something else that may be related. NOWtv videos do not work (UK Broadcaster aka SKY). Top is Thorium and bottom is Firefox working. 

![image](https://github.com/Alex313031/Thorium-Win/assets/79374258/56e6954e-016e-4246-8e50-5c7094b1dce8)

**Comment by Dormant-Hero** [comment]
> This seems to be an issue only in Windows and Mac maybe but not on Linux (probably) - Udemy videos working well in Debian Sid.

It might not be an issue anymore for udemy actually. I reinstalled windows 10 since to try this Atlus OS thing just in case that matters and it is something windows related. Thorium still the same build 117.0.5938.157. 

Udemy (ignore course progression please):

![image](https://github.com/Alex313031/Thorium-Win/assets/79374258/2f3e5741-3696-4707-8e8c-c73a6ab42aca)

Sadly I checked now tv and there is still an issue here:

![image](https://github.com/Alex313031/Thorium-Win/assets/79374258/170b5046-0dad-400d-97a5-77424f08cd86)
