### ISSUE TITLE
unable to install thorium

### ISSUE THREAD

**Issue by tloc241** [Alex313031/Thorium-Win#74]
**System Details**
 - OS: win 10 64bit version 1809
 - Thorium Version 117.0.5938.157

**Problem**
unable to run thorium with mini installer and .bat file from zip

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/112869206/6eec529e-12e9-4d17-844e-5af0f93074e4)
![image](https://github.com/Alex313031/Thorium-Win/assets/112869206/d52ad503-de57-4078-8c27-170902673801)

**Additional Notes**
i'm not sure that this thing happened because of my windows itself or thorium application either ;-;
and i'm not using IDM, i'm download it directly from github, someone plz help me ;-;

**Comment by mattdoot** [comment]
having similiar issue but i get compatability error when i run exe from zip and install doesnt install anything

**Comment by LAPIII** [comment]
Yeah, Thorium is portable only.

**Comment by imoldovavan** [comment]
What does that mean???  I have the same issues on win 10.

**Comment by LAPIII** [comment]
A portable app is a computer program that doesn't need to be installed into Windows like traditional apps, so they run in memory.

**Comment by imoldovavan** [comment]
Thank you. I wish I could get it going. Even running it in admin mode I get the same errors as the op.

**Comment by mattdoot** [comment]
yea i get an error when i run the exe from the zip

**Comment by gz83** [comment]
Your inability to install or use the thorium browser properly may be related to the fact that you are using an incorrect version, please select the version according to the instruction set supported by the processor you are currently using.

**Comment by tloc241** [comment]
@gz83 where can i find the instruction set? is it in readme.txt one? can you help me?

**Comment by gz83** [comment]
You can search for your processor model through a search engine. Generally, detailed parameters of the processor will be recorded on the official website of the processor manufacturer.  If you don't know how to do it, you can also send the processor model here and I will help you choose the version.

@tloc241

**Comment by tloc241** [comment]
my processor model is Intel Pentium Silver N5030, thanks for helpping me 😃
@gz83

**Comment by Alex313031** [comment]
@gz83 @tloc241 @LAPIII UGH this is almost getting annoying. But is it NOT the users fault don't think I am getting mad at y'all. It is intel not including AVX with their lower end processors. Thorium is normally compiled with AVX, but I make SSE3 versions that will run on your CPUs, please see > https://github.com/Alex313031/Thorium-sse3

**Comment by tloc241** [comment]
its working wonderfully now, thanks you so much @Alex313031, love this project after all <3

**Comment by ebintobin** [comment]
Try turning of Windows's defender and installing it, before that whenever I click on the exe file or the batch file, it didn't do anything.

**Comment by salphandon** [comment]
@Alex313031 
Hi I try to install Thorium on Windows 10.
But nothing happens when I run the installer file.
I try to turn off windows defender but this doesn't help.
On second computer I installed it without problems.
Could you please advise what could be the problem ?

PS I have old CPU : AMD Phenom(tm) II X4 970 Processor   3.50 GHz
Could be this a issue ?

**Comment by gz83** [comment]
> @Alex313031 Hi I try to install Thorium on Windows 10. But nothing happens when I run the installer file. I try to turn off windows defender but this doesn't help. On second computer I installed it without problems. Could you please advise what could be the problem ?
> 
> PS I have old CPU : AMD Phenom(tm) II X4 970 Processor 3.50 GHz Could be this a issue ?

https://github.com/Alex313031/Thorium-Win/issues/74#issuecomment-1767803728

This also applies to AMD series processors

**Comment by salphandon** [comment]
@gz83
so I cannot install thorium or should look for specific version ?

**Comment by gz83** [comment]
> @gz83 so I cannot install thorium or should look for specific version ?

Have you carefully read the link I provided above? You can try using SSE3 version

@salphandon

**Comment by salphandon** [comment]
@gz83 
In this link I find only files for linux.
last link:
https://github.com/Alex313031/Thorium-SSE3/releases/tag/migrate
has only 2 zip files with source code.
Or I look in wrong place ?

Could you show me link where are version SSe3 for windows 10 ?

**Comment by gz83** [comment]
> @gz83 In this link I find only files for linux. last link: https://github.com/Alex313031/Thorium-SSE3/releases/tag/migrate has only 2 zip files with source code. Or I look in wrong place ?
> 
> Could you show me link where are version SSe3 for windows 10 ?

You can see it by returning to the release page
https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

@salphandon

**Comment by lanellis** [comment]
I had the exact same problem as the initial post, running Windows 10 Home 22H2 build 19045.3636, but the processor is a 2010 era Intel i3-370M.  Using the SSE3 version worked.

**Comment by workdowg** [comment]
> @gz83 @tloc241 @LAPIII UGH this is almost getting annoying. But is it NOT the users fault don't think I am getting mad at y'all. It is intel not including AVX with their lower end processors. Thorium is normally compiled with AVX, but I make SSE3 versions that will run on your CPUs, please see > https://github.com/Alex313031/Thorium-sse3

When I follow the link, everything is crossed out??? My processor doesn't support AVX2 only sse3, it is an Intel N4020C. Where is the Windows SSE3 build? 

BTW... Thanks for your efforts! I have this working perfectly on Arch with a NUC  Intel(R) Celeron(R) CPU  N3060 and in Windows 11 Intel 12th Gen. Great!!! I just want it on my tablet because of the low ram (4GB).

**Comment by Rushikesh-Malave-183** [comment]
> When I follow the link, everything is crossed out??? My processor doesn't support AVX2 only sse3, it is an Intel N4020C. Where is the Windows SSE3 build?

https://www.intel.com/content/www/us/en/products/sku/214799/intel-celeron-processor-n4020c-4m-cache-up-to-2-80-ghz/specifications.html

If you have win10, use this:
https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1

if you have windows 7 or 8,8.1, use this:
https://github.com/Alex313031/thorium-win7/releases/tag/M109.0.5414.172
download the "thorium_SSE3_mini_installer.exe"

**Comment by Rushikesh-Malave-183** [comment]
also
@gz83 @tloc241 @LAPIII @Alex313031 really sorry for tagging y'all. Don't really know who to tag here
Why not make an automated installer like the original chrome (of google) does? Which will recognise the system processor and download the required files.

**Comment by workdowg** [comment]
> > When I follow the link, everything is crossed out??? My processor doesn't support AVX2 only sse3, it is an Intel N4020C. Where is the Windows SSE3 build?
> 
> https://www.intel.com/content/www/us/en/products/sku/214799/intel-celeron-processor-n4020c-4m-cache-up-to-2-80-ghz/specifications.html
> 
> If you have win10, use this: https://github.com/Alex313031/Thorium-SSE3/releases/tag/M117.0.5938.157-1
> 
> if you have windows 7 or 8,8.1, use this: https://github.com/Alex313031/thorium-win7/releases/tag/M109.0.5414.172 download the "**thorium_SSE3_mini_installer.exe**"

I found the links, I should have closed this. Sorry about that and thank you very much for this! It is a godsend!

**Comment by workdowg** [comment]
> > @gz83 @tloc241 @LAPIII UGH this is almost getting annoying. But is it NOT the users fault don't think I am getting mad at y'all. It is intel not including AVX with their lower end processors. Thorium is normally compiled with AVX, but I make SSE3 versions that will run on your CPUs, please see > https://github.com/Alex313031/Thorium-sse3
> 
> When I follow the link, everything is crossed out??? My processor doesn't support AVX2 only sse3, it is an Intel N4020C. Where is the Windows SSE3 build?
> 
> BTW... Thanks for your efforts! I have this working perfectly on Arch with a NUC Intel(R) Celeron(R) CPU N3060 and in Windows 11 Intel 12th Gen. Great!!! I just want it on my tablet because of the low ram (4GB).
> 
> I'll post on the subreddit also... Prolly a better place to ask.

Got it! I think I just followed the wrong link...
