### ISSUE TITLE
Slower than Chrome in Speedometer 2.1

### ISSUE THREAD

**Issue by mxft** [Alex313031/Thorium-Win#79]
From what I've heard, Thorium should be much faster than Chrome. 
I downloaded M117.0.5938.157 installer and tried to test it. For test to be fair, I imported my Google account into Thorium and waited for it to install all my extensions. I checked if it's excatly the same as in my Chrome and then tested it.

Tests were run on Windows 10 22H2 with Ryzen 7 5700X

**Thorium-Win 117.0.5938.157:**
![image](https://github.com/Alex313031/Thorium-Win/assets/20448459/a1516198-bb75-4421-b298-f2a7ee098b10)

**Google Chrome 118.0.5993.71:**
![image](https://github.com/Alex313031/Thorium-Win/assets/20448459/cac23e49-946e-48fc-8e54-ff354f8e1a6e)

Should it be exactly like this? Or am I doing something wrong?

**Comment by mxft** [comment]
I also tried Edge 118.0.2088.46 just for fun:
![image](https://github.com/Alex313031/Thorium-Win/assets/20448459/8af001b8-48bc-4583-b43c-046d2479879f)

**Comment by gz83** [comment]
It is of little use to compare Thorium with closed-source software such as Chrome and Edge, and browsers with inconsistent versions.

@mxft

**Comment by F474M0R64N4** [comment]
Google Chrome 118.0.5993.71 (64 bit)

![image](https://github.com/Alex313031/Thorium-Win/assets/8020186/7a145b45-48e4-4162-805d-383dfa8502a7)

Thorium 117.0.5938.157 64 bit

![image](https://github.com/Alex313031/Thorium-Win/assets/8020186/fddb716e-15c7-4948-b4bd-3e0491f278ae)

**Comment by mxft** [comment]
@F474M0R64N4 it's weird that my Chrome instance runs better on a weaker CPU. But I'm not surprised Thorium is fast on your benchmark, because this is exactly what's expected of it. I'm just wondering why I don't get the same performance difference between browsers.

**Comment by F474M0R64N4** [comment]
> @F474M0R64N4 it's weird that my Chrome instance runs better on a weaker CPU. But I'm not surprised Thorium is fast on your benchmark, because this is exactly what's expected of it. I'm just wondering why I don't get the same performance difference between browsers.

Disable all extensions

**Comment by mxft** [comment]
> Disable all extensions

Sadly, it didn't work. Results are pretty much the same

**Comment by Sunspire** [comment]
The official websites states that Thorium is faster than vanilla chrome, not google chrome.

"This nets a [8-38% performance](https://thorium.rocks/performance) improvement over **vanilla** Chromium, ... "

**Comment by MaximusPanin** [comment]
In the screenshots I see 503 points. And the speedometer scale is made up to a maximum of 140 points. 
What's wrong ? Maybe the lower the number, the better the result ? Strange implementation of the benchmark.
