### ISSUE TITLE
AVX2 `37fa74d` build is unusable

### ISSUE THREAD

**Issue by etil2jz** [Alex313031/Thorium-Win#8]
Hi,

I updated my Thorium AVX2 setup to version [M101.0.4921.0](https://github.com/Alex313031/Thorium-AVX2/tree/M101.0.4921.0) and now I can't start Thorium, processes crash at start.

![Screenshot of issue](https://i.ibb.co/D88tVCc/Untitled.png)

**Comment by oka1q** [comment]
Use Compatibility Mode with win 7 or 8.

**Comment by Alex313031** [comment]
@oka1q @etil2jz Yep. This is a known upstream bug.

**Comment by Alex313031** [comment]
@etil2jz Does it work ok for you now. Also, future AVX2 issues should now be put in the AVX repo. > https://github.com/Alex313031/Thorium-AVX2

**Comment by etil2jz** [comment]
@Alex313031 Could it be possible to release a new build so I can test?
Right now, using comp mode W7 or W8 works but It still crashes sometimes (i.e. while watching a YouTube video)

**Comment by Alex313031** [comment]
@etil2jz Making a new release today, mate! :)

**Comment by Alex313031** [comment]
@etil2jz  @oka1q New releases uploaded here and in the AVX2 repo.
