### ISSUE TITLE
Where's the Windows installer for the full version (not the mini version) of this browser??

### ISSUE THREAD

**Issue by DiscoFever78** [Alex313031/Thorium-Win#80]
...been googling and scratching my head for 20 minutes now and had to resort to posting this question.

**Comment by gz83** [comment]
mini_installer is the complete installation package

@DiscoFever78

**Comment by Senci83** [comment]
Found out when trying to run the mini_installer .exe that is was flagged as virus from Windows Defender. 
PUADlManager:Win32/Bundlore virus name

**Comment by JimTheTrucker** [comment]
Copied form a YT comment I made.. "**Bummer..tried install from the mini installer 5 times including as admin, nothing. It was blocked  and will not even try to start. Win 10. Any tips? Update: next day thorium.bat was also blocked so no install possible after waiting all night for my slow internet to download it**" Windows defender blocks all attempts

**Comment by kun-create** [comment]
Virustotal: **Ransomware/Win.Magniber.R562052** , **TROJ_GEN.R002V01JA23**
