### ISSUE TITLE
Spotify Not Working

### ISSUE THREAD

**Issue by Crepesman** [Alex313031/Thorium-Win#81]
A couple seconds of only some songs play whereas other songs give you this error: "Spotify can't play this right now. If you have the file on your computer you can import it."

If you go to Chris Titus's video and search comments for "spotify", you will see that others have this same issue.

**Comment by gz83** [comment]
This issue has been moved to the correct repo. The problem of Spotify not being able to play may be related to widevine's VMP verification. For details, see

https://github.com/Alex313031/Thorium-Win/issues/73#issuecomment-1767566078

@Crepesman
