### ISSUE TITLE
Thorium Browsing history 

### ISSUE THREAD

**Issue by Pinoles17** [Alex313031/Thorium-Win#84]
Is there any way that I can hide or not showing my recent browsing history on the search tab?

![Sin título](https://github.com/Alex313031/Alex313031.github.io/assets/138397475/ca08f705-fb1b-41b5-b04e-2317a771957f)

**Comment by gz83** [comment]
Did you restart your browser after disabling these experimental flags?

Also, are you currently logged into your Google account?

One last reminder: do not post Thorium Browser related issues in the Alex313031.github.io repo, Thorium Browser related issues should be discussed in the Thorium Browser repo.

@Pinoles17

**Comment by Pinoles17** [comment]
Yes
Yes
Sorry, I'm not used to Github and this is the first place where I found a comment section:(
@gz83

**Comment by gz83** [comment]
Open chrome://settings/syncSetup and turn off the search-related settings inside.

In addition, go to the Google account management page, delete the activity records, and check again to see if the problem can be solved.

@Pinoles17

**Comment by Pinoles17** [comment]
It didn't work neither :( I still have #omnibox-zero-suggest-prefetching and #omnibox-zero-suggest-prefetching-on-srp turned off btw

**Comment by gz83** [comment]
Try switching your default search engine to something other than Google and see if that solves the problem you're experiencing?

@Pinoles17

**Comment by Pinoles17** [comment]
Nothing changed
@gz83
