### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by lethinhrider** [Alex313031/Thorium-Win#85]
Please add installation method via chocolatey: https://community.chocolatey.org/packages

This is an easy method to install and update via command, and can also be applied to Windows 7.

**Comment by AlecMcCutcheon** [comment]
yes please do

**Comment by zchilds** [comment]
Would be a great option, especially for ease of updates

**Comment by jafuuu** [comment]
+1, still waiting for this.

**Comment by hapnan** [comment]
Hi I have added a package request to [chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1478) and the status is now under review.

**Comment by gdeliana** [comment]
Just please whoever did the request, please correct the name at least.

From: RFP - throium
To: RFP - thorium

**Comment by lethinhrider** [comment]
> Hi I have added a package request to [chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1478) and the status is now under review. for windows 7 i dont have mechine for testing if anyone have feel free to be maintainer

Hello, please use VMware or VirtualBox to install windows 7. If you need the windows 7 iso file, it's here: https://massgrave.dev/windows_7_links.html
Everything you need to prepare windows 7 for the author of Thorium browser is listed here: https://thorium.rocks/win7
If you make an additional chocolatey repo for windows 7, this will also help windows 8.1 users to be able to use and update the Thorium browser. Because windows 8.1 also uses the same Thorium version of windows 7. I hope you consider and create a new chocolatey repo, thank you for everything.

**Comment by lethinhrider** [comment]
I will close this issue because the chocolatey repository for Thorium windows 10 has been created by @hapnan 
Anyone who wants to discuss chocolatey repository for thorium windows 7/8.1 please come here: https://github.com/Alex313031/thorium-win7/issues/9
