### ISSUE TITLE
Bookmark bar is not going away

### ISSUE THREAD

**Issue by gassity** [Alex313031/Thorium-Win#87]
**System Details**
 - OS: Windows 11
 - Thorium Version Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
Bookmark bar on a new blank page is always shown. Tried different themes, reinstall, etc.

**Comment by gz83** [comment]
Can you upload some screenshots related to the problem?

@gassity

**Comment by gassity** [comment]
![Screenshot (10)](https://github.com/Alex313031/Thorium-Win/assets/74508836/660d833c-0ff4-46c0-8777-e085d77b3c88)

**Comment by gz83** [comment]
Check out this website's method below to see if it helps you

https://www.askvg.com/tip-how-to-hide-bookmarks-bar-on-new-tab-page-in-google-chrome/

In addition, you may also need to turn off powerbookmark in chrome://flags

@gassity

**Comment by gassity** [comment]
No. Tried different key names, still it's on by default. Powerbookmark in flags were off already.
