### ISSUE TITLE
Artifacting and Blurry Text

### ISSUE THREAD

**Issue by MrGunman200** [Alex313031/Thorium-Win#88]
**System Details**
 - OS: Windows 10 Pro 21H2 19044.3086
 - Thorium Version: 117.0.5938.157
 - CPU: Ryzen 3900x
 - GPU: Gigabyte 1080ti
 - Ram: 4x16GB G.Skill
 - MB: MPG X570 GAMING EDGE WIFI

**Problem**
Artifacting on videos, other CSS elements, and blurry rendering of text. It's on and off, mouse position seems to have an effect, not sure exactly what though.

First time using Thorium so I am not aware if this is recent or old.

**Screenshots**
Video showing the problem
https://youtu.be/KUBqkhDh7GA

**Additional Notes**
Doesn't happen on a Windows 11 Ghost Spectre VM

**Comment by MrGunman200** [comment]
Ticking off "Use hardware acceleration when available" appears to make the issue go away or reduce the occurrence immensely

**Comment by gz83** [comment]
Since turning on hardware acceleration can help solve or alleviate the problem, keep it turned on.

**Comment by MrGunman200** [comment]
> Since turning on hardware acceleration can help solve or alleviate the problem, keep it turned on.

Turning off* Turning hardware acceleration off appears to have stopped the issue.
