### ISSUE TITLE
Spotify Web Player Issue

### ISSUE THREAD

**Issue by eenlpe1** [Alex313031/Thorium-Win#89]
**System Details**
 - Dell Inspiron 3593
   - CPU: Intel Core i3 10th Gen
   - GPU: Integrated
   - RAM: 8gb RAM
   - OS: Windows 11 Home
 - Thorium Version:117.0.5938.157

**Problem**
Spotify Web Player is not working properly. When the **Play Button** is clicked, it will shuffle continuously for 3–5 times, then stop. After that, it will play the song only for 30 seconds to 1 minute of the song.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/109678010/888fd1a6-727e-4d46-a85c-18f7dea94d2a)

**Additional Notes**
When I click the **Play Button**, a prompt will appear. It says ```Spotify can&#39;t play this right now. If you have the file on your computer, you can import it```.

**Comment by gz83** [comment]
https://github.com/Alex313031/Thorium-MacOS/issues/19

Mark as duplicate
