### ISSUE TITLE
How to enable Sync - FIXED But leaving to provide Information.

### ISSUE THREAD

**Issue by ecsjjgg** [Alex313031/Thorium-Win#9]
None of your recent builds have sync working!

I just says that I have to login to my google account, but nothing happens when I login...

It still says that I have to login to my google account...

**Comment by Alex313031** [comment]
@ecsjjgg  Add yourself to this google group. > https://groups.google.com/u/1/a/chromium.org/g/google-browser-signin-testaccounts

This is per the official documentation at https://www.chromium.org/developers/how-tos/api-keys/#signing-in-to-chromium-is-restricted
