### ISSUE TITLE
Remove google services like ungoogled chromium

### ISSUE THREAD

**Issue by LJGJM** [Alex313031/Thorium-Win#90]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with google services in my browser. It takes up extra storage. I would like to remove all google telemetry (even chrome webstore) and add [https://github.com/NeverDecaf/chromium-web-store/releases/tag/v1.5.4](url) this to decrease telemetry

**Describe the solution you'd like, including relevant patches or source**
I would like Thorium to create a version named ungoogled thorium by using this [https://github.com/NeverDecaf/chromium-web-store/releases/tag/v1.5.4](url) and this [https://github.com/ungoogled-software/ungoogled-chromium-windows](url). I would be happy to test them!

**Additional Notes**
P.S: Here are some things i would like the ability to remove (its ok if you cant) 
![image](https://github.com/Alex313031/Thorium-Win/assets/88922474/91de8fb3-abf6-43f7-ab6f-be561627c2cd)

Just a reminder, im happy to test! Just please keep as much optimizations possible, helps many low end pcs!

**Comment by gz83** [comment]
In order to maintain a better experience, thorium does not adopt the ungoogled mode, but your suggestions are still very much appreciated.

**Comment by LJGJM** [comment]
Ok, is there any way i can ungoogle it?

**Comment by gz83** [comment]
We currently have no plans to maintain ungoogled thorium

@LJGJM

**Comment by LJGJM** [comment]
Ok, but can you list all of the optimisations of thorium? i will try to compile an ungoogled version. Thanks

**Comment by gz83** [comment]
please see https://github.com/Alex313031/thorium/blob/main/infra/PATCHES.md

**Comment by LJGJM** [comment]
Thanks

**Comment by LJGJM** [comment]
Will it be easier to recompile ungoogled chromium with thorium optimisations or recompile thorium with ungoogled

**Comment by gz83** [comment]
Compiling Chromium is a very time-consuming and complex task, and there is no particularly easy way.

**Comment by LJGJM** [comment]
> Compiling Chromium is a very time-consuming and complex task, and there is no particularly easy way.

Ok, i guess ill find a way
