### ISSUE TITLE
Tab arrangement 

### ISSUE THREAD

**Issue by filipposntine** [Alex313031/Thorium-Win#91]
The Tab arrangement is not efficient. Too many steps to find the tab that you are looking for. And in a workflow you can open several tabs.

The Chrome or Firefox or Edge or Open approach is more user friendly. At the top of the browser are all the tabs that you have open without going to to many step searching for it.  

Looking forward to fix with a patch or an option to go in a simpler tab layout approach. 

Keep your great work.

**Comment by gz83** [comment]
I don't know what function you want, you need to provide more information or examples

**Comment by filipposntine** [comment]
![Thorium](https://github.com/Alex313031/Thorium-Win/assets/18518103/686214c8-39f7-4301-bd6d-10f844abfc74)


Something is wrong with the Tab section. On a different Laptop appears normal on my laptop appears like in the photo. I have windows 11. I install it and appear like this I didn't change anything.

**Comment by gz83** [comment]
Please backup all user data, completely uninstall the currently installed version, and re-download and install the latest version in the repo to check again whether the problem exists.

**Comment by filipposntine** [comment]
![Thorium](https://github.com/Alex313031/Thorium-Win/assets/18518103/9bb3b60a-6b47-4c8b-8456-21fb6461307b)

Ok I fixed it. I thought that was the layout of the browser. I had to go to the flags and disable the touch layout. Great job otherwise keep up you great work.

**Comment by gz83** [comment]
Glad to see your issue is resolved.
