### ISSUE TITLE
can't remove unnecessary space below search bar

### ISSUE THREAD

**Issue by Rairof** [Alex313031/Thorium-Win#97]
**System Details**
 - OS: Windows 11 Pro
 - Thorium Version 117.0.5938.157 (Official Build) (64-bit)

**Problem**
A empty place below site search bar seems to exists even after I remove everything from it, which only takes up more space and makes homepage look bad. Hopefully there is a method to hide it.

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Win/assets/107706560/c3db43d3-6498-40bf-9a62-7095aaae3601)

on any other sites-
![image](https://github.com/Alex313031/Thorium-Win/assets/107706560/9ac26b50-d64a-4df5-8af3-2d20e9218486)

**Additional Notes**
N/A

**Comment by gz83** [comment]
#87
