### ISSUE TITLE
Fail to import browsing history from Firefox Browser on Windows 11

### ISSUE THREAD

**Issue by domeniczz** [Alex313031/Thorium-Win#99]
**System Details**

 - OS: Windows 11 Pro 22H2 build 22621.2428
 - Thorium Version: 117.0.5938.157

**Problem**

Fail to import browsing history from Firefox Browser on Windows 11.
I tried several times, doesn't work. It works well on Chrome browser (118.0.5993.89 (Official Build))

**Additional Notes**

I was trying to import browsing history because I've accidently cleared it, and I tried to import history from FireFox immediately after that.

I'm really sorry I don't know what additional debug info to provide, there're no crashdumps, no error message. If there should be any log file or something else stored on my computer, let me know and I'll as much as I can.

No one encountered this weird issue before?

**Comment by gz83** [comment]
Sorry, I currently do not have a corresponding test environment locally. Keep this question open to receive more responses.
